### PR TITLE
fix preempt & reclaim shecduler plugin with PreemptPredicateFn

### PR DESCRIPTION
**Pull request by LivingCcj**
fix issue: [https://github.com/volcano-sh/volcano/issues/3329](https://github.com/volcano-sh/volcano/issues/3329)

### CODE REVIEW

**Comment by Monokaix** [comment]
The url in description seems not exists: )

**Comment by LivingCcj** [comment]
> The url in description seems not exists: )

thx for your reply, now has updated this url

**Comment by lowang-bh** [comment]
I don't recommend this changed. But I also have no good idea now -_-

**Comment by lowang-bh** [comment]
we need to add some uts to cover it.

**Pull request closed without merging**
