### PR TITLE
add multi-arch image

### PR DESCRIPTION
**Pull request by ccchenjiahuan**
This pr has some notable changes:
* Remove the webhook base image
* Remove `installer/volcano-development-arm64.yaml` and arm specified images , because we don't need them anymore

Signed-off-by: ccchenjiahuan <chenjiahuan163@163.com>

### CODE REVIEW

**Comment by ccchenjiahuan** [comment]
The tested multi-arch images, it works fine in my local envs:
* cccccccjh/vc-webhook-manager:cfdb71617741d657486293f751b0910cd28d6306
* cccccccjh/vc-scheduler:cfdb71617741d657486293f751b0910cd28d6306
* cccccccjh/vc-controller-manager:cfdb71617741d657486293f751b0910cd28d6306

The CI seems that the docker in minikube doesn't support buildkit? l tried but cannot figure it out, anyone knows how to avoid this?

**Review by shinytang6 — CHANGES_REQUESTED** [review]
The implementations LGTM overall. Need to pass the CI before merging

**Comment by shinytang6** [comment]
> The tested multi-arch images, it works fine in my local envs:
> 
> * cccccccjh/vc-webhook-manager:cfdb71617741d657486293f751b0910cd28d6306
> * cccccccjh/vc-scheduler:cfdb71617741d657486293f751b0910cd28d6306
> * cccccccjh/vc-controller-manager:cfdb71617741d657486293f751b0910cd28d6306
> 
> The CI seems that the docker in minikube doesn't support buildkit? l tried but cannot figure it out, anyone knows how to avoid this?
> 
> image links: https://hub.docker.com/u/cccccccjh

Yes, seems that `docker buildx` command is not supported in minikube.
@Thor-wl @william-wang @hwdef @Yikun Any ideas about the CI `E2E Spark Integration Test` case failure?

**Comment by Yikun** [comment]
If we support the buildx, we need install buildx to support on spark e2e test like: https://github.com/volcano-sh/volcano/pull/2438

**Comment by Yikun** [comment]
@ccchenjiahuan Thanks for your work!

Feel free to squash https://github.com/volcano-sh/volcano/pull/2438 in your pr, I did a e2e test with spark + buildx installation: https://github.com/volcano-sh/volcano/pull/2438 , it works!

**Comment by Yikun** [comment]
and `E2E Sequence Jobs / E2E about Sequence (pull_request) Failing after 32m` seems failed due to flaky test maybe @Thor-wl could do a double confirm

**Comment by Yikun** [comment]
I also do a test manually in an arm64 env (apple M1):
```shell
$ minikube start --cpus 4 --memory 6144
$ eval $(minikube docker-env)
$ make TAG=latest update-development-yaml
$ make TAG=latest images
$ k apply -f ~/code/volcano/installer/volcano-development.yaml

$ docker inspect volcanosh/vc-scheduler | grep Architecture
        "Architecture": "arm64",
$ docker inspect volcanosh/vc-controller-manager | grep Architecture
        "Architecture": "arm64",
$ docker inspect volcanosh/vc-webhook-manager | grep Architecture
        "Architecture": "arm64",

$ k get pod -A | grep volcano
volcano-system   volcano-admission-56d746f6d-kt4rd                        1/1     Running     0             35m
volcano-system   volcano-admission-init-5lnbt                             0/1     Completed   0             35m
volcano-system   volcano-controllers-7c79f98f4-5jxk2                      1/1     Running     0             35m
volcano-system   volcano-scheduler-598bfd9df4-bgdmr                       1/1     Running     0             35m
```

Spark e2e test also work:
```
$ build/sbt -Pvolcano -Pkubernetes -Pkubernetes-integration-tests -Dspark.kubernetes.test.namespace=default -Dspark.kubernetes.test.deployMode=minikube -Dtest.include.tags=volcano "kubernetes-integration-tests/test"
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[info] KubernetesSuite:
[info] VolcanoSuite:
[info] - Run SparkPi with volcano scheduler (9 seconds, 380 milliseconds)
[info] - SPARK-38187: Run SparkPi Jobs with minCPU (21 seconds, 522 milliseconds)
[info] - SPARK-38187: Run SparkPi Jobs with minMemory (23 seconds, 454 milliseconds)
[info] - SPARK-38188: Run SparkPi jobs with 2 queues (only 1 enabled) (13 seconds, 350 milliseconds)
[info] - SPARK-38188: Run SparkPi jobs with 2 queues (all enabled) (22 seconds, 332 milliseconds)
[info] - SPARK-38423: Run driver job to validate priority order (16 seconds, 299 milliseconds)
[info] Run completed in 1 minute, 52 seconds.
[info] Total number of tests run: 6
[info] Suites: completed 2, aborted 0
[info] Tests: succeeded 6, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 177 s (02:57), completed 2022-8-15 17:23:24
```

**Comment by Yikun** [comment]
BTW, this might bring some behavior changes:
- Drop the base image
- Replace `k apply -f installer/volcano-development-arm64.yaml` with `k apply -f installer/volcano-development.yaml`
- Drop the arm specific image
- Release process cc @Thor-wl

We'd better note in doc, release note or somewhere to mention them.

**Comment by Thor-wl** [comment]
Generally LGTM for me. Looking forward to other reviewers' advices.

**Review by Thor-wl — COMMENTED** [review]
Generally LGTM for me. Looking forward to other reviewers' advices.

**Review by shinytang6 — COMMENTED** [review]
Thanks, also LGTM

**Comment by shinytang6** [comment]
Another thing to check is whether the CI `Daily Release` work after merged

**Review by Thor-wl — APPROVED** [review]

**Comment by Yikun** [comment]
And also changes the doc https://volcano.sh/en/docs/installation/#install-with-yaml-files

**Comment by Thor-wl** [comment]
> And also changes the doc https://volcano.sh/en/docs/installation/#install-with-yaml-files

Yes. @ccchenjiahuan Can you submit another PR to update the doc?

**Comment by hwdef** [comment]
I tested this on m2 macbook air and  and an amd64 virtual machine. It can work.

**Comment by shinytang6** [comment]
btw, `daily release` failed, please also help check it out.
https://github.com/volcano-sh/volcano/runs/7889767385?check_suite_focus=true

**Comment by SoutherLea** [comment]
With this solution, each component will download the project's dependency package when it is built. If for some well-known reason, the download can easily fail due to network instability. In this case, it is difficult to successfully build images. :-P

**Pull request merged**
