### PR TITLE
[cherry-pick for release-1.10]fix pg controller create redundancy podGroup when schedulerName isn't matched

### PR DESCRIPTION
**Pull request by liuyuanchun11**
fix issue https://github.com/volcano-sh/volcano/issues/3671

cherry-pick from https://github.com/volcano-sh/volcano/pull/3672

Check whether the value of pod.spec.schedulerName is matched before creating a podGroup.

### CODE REVIEW

**Review by hwdef — COMMENTED** [review]
I think when cherrypick, the source branch should be master

**Comment by hwdef** [comment]
cherrypick should operate on only one commitId, not multiple commitIDs

/hold

**Comment by liuyuanchun11** [comment]
> cherrypick should operate on only one commitId, not multiple commitIDs
> 
> /hold

**Comment by liuyuanchun11** [comment]
> cherrypick should operate on only one commitId, not multiple commitIDs
> 
> /hold

It's cherry-pick from the master branch.

**Comment by hwdef** [comment]
image

image

But the commit ID is not same. Did I get something wrong?

**Comment by liuyuanchun11** [comment]
> image
> 
> image
> 
> But the commit ID is not same. Did I get something wrong?

As far as I know, the git cherry-pick operation creates a new commit ID, while only git merge or rebase can preserve the original commit ID. However, merge or rebase are typically used for batch modifications or synchronization, whereas I currently only need to synchronize a single commit. Perhaps you could demonstrate how to perform this operation?

**Comment by hwdef** [comment]
Sorry, It was my mistake and you were right

**Pull request merged**
