### PR TITLE
modify code comment

### PR DESCRIPTION
**Pull request by pikachu-lemon**

### CODE REVIEW

**Comment by xiao-jay** [comment]
@pikachu-lemon you should add -s in git commit ,such as git commit -s -m "xxxx" to pass the DCO ci error.
LGTM.

**Comment by pikachu-lemon** [comment]
Thank you. There is a problem with my current user's signature, I will close this pr and resubmit.

**Comment by pikachu-lemon** [comment]
> @pikachu-lemon you should add -s in git commit ,such as git commit -s -m "xxxx" to pass the DCO ci error. LGTM.

Thank you. There is a problem with my current user's signature, I will close this pr and resubmit.

**Comment by pikachu-lemon** [comment]
this is the new pr #2847 ，thanks.

**Pull request closed without merging**
