### PR TITLE
update version compatibility instructions for volcano v1.8 version su…

### PR DESCRIPTION
**Pull request by Mufengzhe**
update version compatibility instructions for volcano v1.8 version support for k8s v1.27 and v1.28

### CODE REVIEW

**Review by hwdef — COMMENTED** [review]
volcano 1.7 support k8s 1.27 and 1.28

**Comment by Mufengzhe** [comment]
> volcano 1.7 support k8s 1.27 and 1.28

That right, i have updated it

**Review by jiangkaihua — APPROVED** [review]

**Review by william-wang — APPROVED** [review]
/lgtm

**Pull request merged**
