### PR TITLE
fix vcjob not work when mount volume

### PR DESCRIPTION
**Pull request by Thor-wl**
fix: https://github.com/volcano-sh/volcano/issues/1609
Signed-off-by: Thor-wl <13164644535@163.com>

### CODE REVIEW

**Comment by hwdef** [comment]
Why do we need to update pvc, please explain the reason.

**Comment by Thor-wl** [comment]
> Why do we need to update pvc, please explain the reason.

PVC not existing will be created automatically by volcano such as the `pvSpec` specified in e2e "use exisisting PVC in job". That's the root reason why that case cannot pass ever.

**Review by william-wang — APPROVED** [review]
/lgtm

**Comment by hwdef** [comment]
But when vcjob is bound to an existing pvc, there will be this problem.

**Pull request merged**
