### PR TITLE
:recycle: rewrite all the action tests with CreateCacheForTest and TestArg

### PR DESCRIPTION
**Pull request by kingeasternsun**
I refactor the code that build schedule cache  in each test cases by using a common function CreateCacheForTest, so the test code is more clear

### CODE REVIEW

**Comment by lowang-bh** [comment]
Good idea and thanks your contribution. Would you please also put those code about building Queue and podgroug to a function so that there are fewer code lines?

**Comment by kingeasternsun** [comment]
> Good idea and thanks your contribution. Would you please also put those code about building Queue and podgroug to a function so that there are fewer code lines?

ok， I will improve it

**Comment by kingeasternsun** [comment]
`CreateCacheForTest ` can not placed int the package of "pkg/scheduler/util" whichi will cause import cycle, so I move it to cache

**Comment by kingeasternsun** [comment]
looks strange ,  i pass test in my local host

```
E0609 15:45:20.919412   49994 utils.go:43] init kubeclient in 4pdvgpu failed%!(EXTRA string=stat /home/codespace/.kube/config: no such file or directory)
=== RUN   TestAllocate
=== RUN   TestAllocate/one_Job_with_two_Pods_on_one_node
=== NAME  TestAllocate
    allocate_test.go:251: Test cases are not as expected, fixed later. see issue: #2810
--- SKIP: TestAllocate (0.00s)
    --- PASS: TestAllocate/one_Job_with_two_Pods_on_one_node (0.00s)
=== RUN   TestAllocateWithDynamicPVC
    allocate_test.go:399: Test cases are not as expected, fixed later. see issue: #2812
--- SKIP: TestAllocateWithDynamicPVC (0.00s)
PASS
ok      volcano.sh/volcano/pkg/scheduler/actions/allocate       0.069s
```

**Comment by kingeasternsun** [comment]
Hi ， @Thor-wl @shinytang6，could u review this， thanks

**Comment by lowang-bh** [comment]
> > Good idea and thanks your contribution. Would you please also put those code about building Queue and podgroug to a function so that there are fewer code lines?
> 
> ok， Thanks for your suggestions. Could I lease these as another PR? or there are too many modifications

I think it's ok to put them in this PR. Anyway, it's up to you.

**Comment by hwdef** [comment]
> > > Good idea and thanks your contribution. Would you please also put those code about building Queue and podgroug to a function so that there are fewer code lines?
> > 
> > 
> > ok， Thanks for your suggestions. Could I lease these as another PR? or there are too many modifications
> 
> I think it's ok to put them in this PR. Anyway, it's up to you.

There are enough codes for this pr, please reduce some review pressure😂

**Comment by kingeasternsun** [comment]
> > > > Good idea and thanks your contribution. Would you please also put those code about building Queue and podgroug to a function so that there are fewer code lines?
> > > 
> > > 
> > > ok， Thanks for your suggestions. Could I lease these as another PR? or there are too many modifications
> > 
> > 
> > I think it's ok to put them in this PR. Anyway, it's up to you.
> 
> There are enough codes for this pr, please reduce some review pressure😂
Thanks @hwdef

**Review by hwdef — COMMENTED** [review]
/lgtm
Looks generally OK

**Review by hwdef — COMMENTED** [review]
/lgtm

**Comment by kingeasternsun** [comment]
Thans @hwdef for your review, But something wrong happend with E2E Spark Integration Test

**Comment by hwdef** [comment]
This seems to be a common error, now all PRs are stuck in this CI

**Review by hwdef — COMMENTED** [review]
/lgtm

**Comment by hwdef** [comment]
When is this pr ready to be reviewed, I don't want to add the lgtm tag multiple times, I've added it three times, if it's not ready to be reviewed, please add the WIP

**Comment by kingeasternsun** [comment]
sorry for that, Because each time when I found lgtm been added, this pr not auto merged because out of date, I have to rebase it, which cause the lgtm bedn removed.

**Comment by hwdef** [comment]
> hi @hwdef, sorry for that, Because most time when lgtm been added, this pr could not auto merged because `This branch is out-of-date with the base branch`, I have to rebase it, which cause the lgtm been removed.

As long as there are no conflicts, it doesn't matter if you fall behind the main branch

**Comment by kingeasternsun** [comment]
hi @merryzhou @zen-xu will u review and appove these pr please, thanks

**Review by hwdef — COMMENTED** [review]
/lgtm

**Comment by hwdef** [comment]
still need

**Comment by kingeasternsun** [comment]
still need

**Comment by kingeasternsun** [comment]
I found someone has used my code  and has merged, the only difference is that the new code was place in pkg/scheduler/cache instead pkg/scheduler/util

**Comment by kingeasternsun** [comment]
Reoepn a New PR https://github.com/volcano-sh/volcano/pull/3249 in here @hwdef

**Pull request closed without merging**
