### PR TITLE
Scheduler api cleanup

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
Fix: #1007

The internal API was introduced when we have two groups of API, and in that case, CRD can not be used to convert them.

This removes all these codes.

### CODE REVIEW

**Comment by k82cn** [comment]
/hold

Why introduce version into scheduler core ?

**Comment by hzxuzhonghu** [comment]
No one else should use an internal version instead of kube-apiserver.  The internal version is used to do validation and convert between two versions. Obviously, we donot want to convert v1beta1 PodGroup/ Queue to an internal version. This step is useless for a client

**Comment by k82cn** [comment]
we decoupled k8s version from volcano version.

**Comment by hzxuzhonghu** [comment]
IMO, it is not decouple, it is duplicate and introduce extra conversion cost.  cc @kevin-wangzefeng

**Comment by hzxuzhonghu** [comment]
@k82cn @william-wang Scheduler as a client of k8s, we donot need to keep a private version and convert between k8s version and our own. And we donot need to list-watch multi-version resources even if we have in the future.  This is much like the way deployment controller does.

**Pull request closed without merging**
