### PR TITLE
clean up build podgroup/queue code, replace with func

### PR DESCRIPTION
**Pull request by lowang-bh**
/kind cleanup

clean code

### CODE REVIEW

**Comment by lowang-bh** [comment]
@wangyang0616 @hwdef @william-wang Please take a look, thanks.

**Comment by lowang-bh** [comment]
/priority/high

**Review by hwdef — COMMENTED** [review]
/lgtm

**Comment by kingeasternsun** [comment]
may be this PR should be merged after this https://github.com/volcano-sh/volcano/pull/2901？

**Comment by hwdef** [comment]
> may be this PR should be merged after this #2901 ？

yes

/hold 

wait until https://github.com/volcano-sh/volcano/pull/2901 is merged

**Comment by kingeasternsun** [comment]
@lowang-bh @hwdef  HI, the PR https://github.com/volcano-sh/volcano/pull/2901 has rewrite with https://github.com/volcano-sh/volcano/pull/3249

**Pull request closed without merging**
