### PR TITLE
Remove deprecated Ginkgo options --progress and --slow-spec-threshold

### PR DESCRIPTION
**Pull request by SherlockShemol**
When I pr https://github.com/volcano-sh/volcano/pull/3811 and I find the E2E tests failed.When I investigate the problem,  I find
```
You're using deprecated Ginkgo functionality:
=============================================
  --progress is deprecated .  The functionality provided by --progress was confusing and is no longer needed.  Use --show-node-events instead to see node entry and exit events included in the timeline of failed and verbose specs.  Or you can run with -vv to always see all node events.  Lastly, --poll-progress-after and the PollProgressAfter decorator now provide a better mechanism for debugging specs that tend to get stuck.
  --slow-spec-threshold is deprecated --slow-spec-threshold has been deprecated and will be removed in a future version of Ginkgo.  This feature has proved to be more noisy than useful.  You can use --poll-progress-after, instead, to get more actionable feedback about potentially slow specs and understand where they might be getting stuck.
```
This pr is to remove deprecated Ginkgo options --progress and --slow-spec-threshold.

### CODE REVIEW

**Comment by SherlockShemol** [comment]
For your reference: https://github.com/onsi/ginkgo/blob/master/CHANGELOG.md#250

**Review by hwdef — COMMENTED** [review]
/ok-to-test

**Comment by hwdef** [comment]
But there are other errors in CI

**Comment by SherlockShemol** [comment]
> But there are other errors in CI

Could this be due to resource limitations in the CI environment? It seems like the jobs are failing due to pods not being ready in time.Or it's because of some  resource allocation or scheduling problem.

**Comment by hwdef** [comment]
I'll check this

**Comment by JesseStutler** [comment]
Please rebase the new master branch because CI has been fixed: https://github.com/volcano-sh/volcano/pull/3817

**Comment by SherlockShemol** [comment]
> Please rebase the new master branch because CI has been fixed: #3817

rebased.

**Comment by hwdef** [comment]
Please modify the describe. delete some useless errors. Such as,
```
  [FAILED] Unexpected error:
      <*errors.errorString | 0xc0005117f0>: 
      [Wait time out]: expected job 'qj-1' to have 2 ready pods, actual got 0
      {
          s: "[Wait time out]: expected job 'qj-1' to have 2 ready pods, actual got 0",
      }
  occurred
```

**Comment by SherlockShemol** [comment]
> Please modify the describe. delete some useless errors. Such as,
> 
> ```
>   [FAILED] Unexpected error:
>       <*errors.errorString | 0xc0005117f0>: 
>       [Wait time out]: expected job 'qj-1' to have 2 ready pods, actual got 0
>       {
>           s: "[Wait time out]: expected job 'qj-1' to have 2 ready pods, actual got 0",
>       }
>   occurred
> ```

modified.

**Review by hwdef — COMMENTED** [review]
/lgtm
/ok-to-test

**Comment by Monokaix** [comment]
Is there some changs of ginkgo output for users when these flags are removed and new flags are added?

**Comment by SherlockShemol** [comment]
> Is there some changs of ginkgo output for users when these flags are removed and new flags are added?

```
 Ginkgo's console output is not guaranteed to be stable for tooling and automation purposes. You should, instead, use Ginkgo's JSON format to build tooling on top of as it has stronger guarantees to be stable from version to version.
```
Yes, the console output may change and it has stronger guarantees if using the JSON format to build tooling on top of.

**Pull request closed without merging**
