### PR TITLE
upgrade spf13/cobra version to 1.2.1

### LINKED ISSUE #1798: spf13/cobra  is too old to use, need update.
What happened:

Active reliance on software is too old. github.com/spf13/cobra v1.0.0 is publish on 20 Oct 2019, and newest is v1.2.1
 [cobra/blob](https://github.com/spf13/cobra/blob/v1.0.0/go.sum)

Environment:

```
Volcano Version: v1.4.0
Kubernetes version (use kubectl version):1.22,1.22.1
Go: 1.17,1.17.1
```

### PR DESCRIPTION
**Pull request by marffin**
fix #1798

### CODE REVIEW

**Comment by marffin** [comment]
DCO fixed

**Comment by marffin** [comment]
Yeah, I've run `go mod tidy` and also `make` and `make unit-test` locally, seems good

**Comment by Thor-wl** [comment]
Please execute `go mod vendor` to update the vendor

**Comment by marffin** [comment]
Tried to run e2e test locally but hit GFW.

**Comment by marffin** [comment]
@shinytang6 need your approval [smile]

**Pull request merged**
