### PR TITLE
enhancement: add keyword about allocate/pipeline/evict information in log

### PR DESCRIPTION
**Pull request by lowang-bh**
add key word about allocate/pipeline/evict information in log.

### CODE REVIEW

**Comment by wangyang0616** [comment]
It's ok to me, please help to review.
cc @william-wang @jiangkaihua

**Comment by lowang-bh** [comment]
close

**Comment by lowang-bh** [comment]
reopen.

**Comment by lowang-bh** [comment]
Hi, @Thor-wl and @merryzhou , would you please help to review this pr? thanks.

**Comment by jiangkaihua** [comment]
/lgtm

Maybe we need to make the CI happy first. @wangyang0616

**Review by hwdef — COMMENTED** [review]
/lgtm

**Comment by lowang-bh** [comment]
Hi, @william-wang would you please help to review this pr and merge it? Thanks.

**Review by william-wang — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
