### PR TITLE
Fix: All pods is existing when restart count exceed max retry

### PR DESCRIPTION
**Pull request by LuBingtan**
Fix: https://github.com/volcano-sh/volcano/issues/1718

### CODE REVIEW

**Comment by Thor-wl** [comment]
I think this issue should be discussed in the community. I'll take it in the weekly meeting.

**Comment by Thor-wl** [comment]
When I tried to reproduce the phenomenon mentioning at https://github.com/volcano-sh/volcano/issues/1736, I found that the mpi master was compeleted but workers were still running when maxretry is 1.

**Comment by william-wang** [comment]
@LuBingtan Thanks for your pr. Is there e2e case to track this case? If not, please add the e2e or add your testing results to make sure it playing well with the case in pr 1657.

**Comment by LuBingtan** [comment]
> @LuBingtan Thanks for your pr. Is there e2e case to track this case? If not, please add the e2e or add your testing results to make sure it playing well with the case in pr 1657.

Ok, I will add an e2e testing case

**Comment by igormishsky** [comment]
Can someone see why it is not merged?
We also have this issue

**Comment by jasonliu747** [comment]
> Can someone see why it is not merged? We also have this issue

Waiting for more test results.

**Comment by LuBingtan** [comment]
@jasonliu747 @william-wang @Thor-wl 

Hi, I have updated this pr with an e2e test for job retry.
Please take a look

**Comment by LuBingtan** [comment]
@jasonliu747 @william-wang @Thor-wl
Hi, is there any suggestions?  I wander how this PR could be merged?

**Comment by Thor-wl** [comment]
I'm OK about current PR. 
/cc @shinytang6 @william-wang @jasonliu747 Pls take a review.

**Review by jasonliu747 — COMMENTED** [review]
/lgtm

**Comment by LuBingtan** [comment]
@shinytang6 @william-wang 
Hi~ Could you help me to take a look ?

**Review by william-wang — APPROVED** [review]
/lgtm

**Pull request merged**
