### PR TITLE
support multi-cluster scheduling in framework

### PR DESCRIPTION
**Pull request by william-wang**
Signed-off-by: william-wang <wang.platform@hotmail.com>

### CODE REVIEW

**Comment by shinytang6** [comment]
Will there be some design doc for this?

**Comment by Thor-wl** [comment]
> Will there be some design doc for this?

+1
/lgtm

**Comment by k82cn** [comment]
> Will there be some design doc for this?

+1, @william-wang , would you help to share more info on this PR?

**Comment by william-wang** [comment]
> 
> +1, @william-wang , would you help to share more info on this PR?

Of course, i'd like to provide a doc for this.

**Pull request merged**
