### PR TITLE
"path" spell error

### PR DESCRIPTION
**Pull request by zhuyaguang**
path 单词拼写错误

### CODE REVIEW

**Review by shinytang6 — APPROVED** [review]
Thanks for your contribution!
/lgtm
/approve

**Review by jasonliu747 — COMMENTED** [review]
Hi, please follow the instruction to fix DCO error. Otherwise we can't merge this awesome PR.

**Review by william-wang — APPROVED** [review]

**Review by shinytang6 — APPROVED** [review]

**Review by jasonliu747 — APPROVED** [review]
/lgtm

**Comment by jasonliu747** [comment]
@zhuyaguang CI has some issues. Don't worry, we'll take care of it.

**Comment by Thor-wl** [comment]
> @zhuyaguang CI has some issues. Don't worry, we'll take care of it.

CI has already run.

**Pull request merged**
