### PR TITLE
feat: allow configuration of ipFamilyPolicy

### PR DESCRIPTION
**Pull request by dongjiang1989**
support dualstack with helm charts deployment

### CODE REVIEW

**Comment by Monokaix** [comment]
Please also update `installer/README.md`.

**Comment by dongjiang1989** [comment]
> Please also update `installer/README.md`.

Thanks. @Monokaix 
Done.

**Comment by Monokaix** [comment]
Hi please squash to one commit.

**Comment by dongjiang1989** [comment]
> Hi please squash to one commit.

Thanks. Git Squash done.

**Review by hwdef — COMMENTED** [review]
/approve

**Pull request merged**
