### PR TITLE
add a argument csi-storage to control the storage capacity resource

### PR DESCRIPTION
**Pull request by huone1**
Signed-off-by: huone1 <huwanxing@huawei.com>
1. add a argument csi-storage to control the storage capacity resource, because storage capacity is  disable by default in k8s 1.19 and is enable  by default in k8s 1.21
   if volcano is installed in k8s 1.19, it will happen as the following:
   
image

  
2. delete the  repeated rules

### CODE REVIEW

**Comment by Thor-wl** [comment]
After the k8s vendor is upgraded to v1.22, it will be open by default. Then I will remove the parameter. It works for v1.19 temporarily.
/lgtm

**Review by william-wang — APPROVED** [review]
/lgtm

**Pull request merged**
