### PR TITLE
fix: allocated field in queue status is calcutated error

### PR DESCRIPTION
**Pull request by shusley244**
The allocated field in the queue status should be calculated based on tasks with the status "bound", "binding", "allocated", and "running".

If the container is slow to be running status (such as stuck on image pull stage), we can't obtain the correct value for the allocated field from the queue status even if volcano is finished to scheduler the task.

### CODE REVIEW

**Comment by lowang-bh** [comment]
/lgtm

Is there any test results?

**Review by lowang-bh — APPROVED** [review]

**Comment by shusley244** [comment]
> /lgtm
> 
> Is there any test results?

yes, I applied the change to my prod environment one month ago, everything is fine.

**Comment by shusley244** [comment]
@lowang-bh can you review again ? I fixed the dco check.

**Comment by shusley244** [comment]
@k82cn @william-wang @hwdef 
Would please help to review it?

**Comment by william-wang** [comment]
@shusley244 Thanks for your contribution. please cherry-pick this pr to release-1.8 branch.

**Review by william-wang — APPROVED** [review]
/approve

**Comment by shusley244** [comment]
> @shusley244 Thanks for your contribution. please cherry-pick this pr to release-1.8 branch.

ok, thanks for your approve ~

new pr: https://github.com/volcano-sh/volcano/pull/3221

**Pull request closed without merging**
