### PR TITLE
Add options: worker-threads-for-gc

### PR DESCRIPTION
**Pull request by WulixuanS**
A option to adjust the concurrency of gc

### CODE REVIEW

**Comment by lowang-bh** [comment]
Shall we need to validate the param?

**Comment by WulixuanS** [comment]
> Shall we need to validate the param?

Do you mean to limit the param range?

**Comment by lowang-bh** [comment]
> > Shall we need to validate the param?
> 
> Do you mean to limit the param range?

Yes.

**Review by william-wang — APPROVED** [review]
/approve

**Pull request merged**
