### PR TITLE
fix scheduler metric e2e_scheduling_latency_milliseconds

### LINKED ISSUE #2969: scheduler metric e2e_scheduling_latency_milliseconds not correct
**What happened**:
volcano scheduler metric: e2e_scheduling_latency_milliseconds not correct.
**What you expected to happen**:
e2e_scheduling_latency_milliseconds now only includes open session costs, should also include closed session costs.
image

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by WulixuanS**
fix #2969

### CODE REVIEW

**Comment by lowang-bh** [comment]
LGTM. @william-wang @wangyang0616 please help to review. Thanks.

**Comment by hwdef** [comment]
> LGTM. @hwdef @wangyang0616 please help to review. Thanks.

You are already a reviewer.
You can use `/lgtm` command to add lgtm label.

**Comment by lowang-bh** [comment]
> You are already a reviewer. You can use `/lgtm` command to add lgtm label.

Yes，I mean it's better to have 2-3 lgtms each pr.

/lgtm

**Comment by hwdef** [comment]
> > You are already a reviewer. You can use `/lgtm` command to add lgtm label.
> 
> Yes，I mean it's better to have 2-3 lgtms each pr.
> 
> /lgtm

In principle, we only need one lgtm and one approve.

If we need more lgtm, you know, then PR will be harder to merge.

**Review by william-wang — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
