### PR TITLE
Improve: reduce calculation of total nodes' resource in stead of storing it when snapshot

### PR DESCRIPTION
**Pull request by lowang-bh**
storing total nodes' resource when snapshot in case of each plugins calculate it 

Signed-off-by: lowang_bh <lhui_wang@163.com>

### CODE REVIEW

**Review by wpeng102 — APPROVED** [review]
/lgtm

**Review by shinytang6 — APPROVED** [review]
/lgtm
/approve

**Comment by jasonliu747** [comment]
@lowang-bh please refer this: https://github.com/volcano-sh/volcano/pull/1574#issuecomment-880075201
Sorry for any inconvenience.

**Review by jasonliu747 — APPROVED** [review]
/lgtm

**Review by shinytang6 — APPROVED** [review]

**Pull request merged**
