### PR TITLE
update PriorityClass from v1beta1 to v1 for go-client

### PR DESCRIPTION
**Pull request by lc2705**
Signed-off-by: lc2705 <liuchang2705@163.com>

### CODE REVIEW

**Comment by lc2705** [comment]
fix the problem left from #1893

**Comment by huone1** [comment]
> /assign @huone1
Please make a test for PriorityClass(v1beta1) to check whether the Convert is normal from v1beta1 to v1 in k8s 1.19.

**Comment by lc2705** [comment]
image
 
image



i test the PriorityClass of v1beta1 (as shown below) in k8s 1.18 1.19 and 1.21, it all works well :)

```
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000
globalDefault: false
description: "high priority for volcano"
```

**Pull request merged**
