### PR TITLE
Update how_to_use_gpu_sharing.md

### PR DESCRIPTION
**Pull request by Lost-Town**
Default setting is the same as setting --gpu-strategy=share.

### CODE REVIEW

**Review by shinytang6 — APPROVED** [review]
yes, you are right
/approve

**Comment by shinytang6** [comment]
BTW, please fix the DCO

**Comment by Lost-Town** [comment]
@shinytang6 thx. It's my first PR here.Sorry for my fault.

**Review by shinytang6 — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
