### PR TITLE
Add Compatibility matrix based on the client-go version used

### PR DESCRIPTION
**Pull request by jwcesign**
Signed-off-by: jiang wei <jwcesign@gmail.com>

## what change
* Add Kubernetes compatibility based on the client-go version used

### CODE REVIEW

**Comment by jwcesign** [comment]
cc @Thor-wl

**Review by hwdef — COMMENTED** [review]
Is there a test result of 1.24? 1.24 is the latest k8s version.

**Comment by hwdef** [comment]
This test result gives me a feeling that volcano is not perfectly compatible with most k8s versions. I don't know if this is a test issue or a volcano issue.

**Comment by jwcesign** [comment]
> Is there a test result of 1.24? 1.24 is the latest k8s version.

I just check the version of client-go used, and then find the compatibility matrix from client-go repo.

**Comment by hwdef** [comment]
https://github.com/karmada-io/karmada#kubernetes-compatibility

volcano compatibility looks terrible compared to karmada

**Pull request closed without merging**
