### PR TITLE
move scheduler name out of common args

### PR DESCRIPTION
**Pull request by lminzhw**
`--scheduler` is common argument now, so it can be parsed in any command ignoring that most of them do not use it at all.

So, this PR move this argument out of common argument and add it on demand for command which use it before.

And, add support for `vkctl job list` to list job with specified scheduler name.

### CODE REVIEW

**Comment by TommyLike** [comment]
Do we have the case that a volcano job is not scheduled by `kube-batch`?

**Comment by lminzhw** [comment]
> Do we have the case that a volcano job is not scheduled by `kube-batch`?

Following our best practice, all the job should use kube-batch.

But we have field `job.spec.schedulerName` to change the default behavior, so I think this logic should be supported all around.

**Comment by TommyLike** [comment]
> > Do we have the case that a volcano job is not scheduled by `kube-batch`?
> 
> Following our best practice, all the job should use kube-batch.
> 
> But we have field `job.spec.schedulerName` to change the default behavior, so I think this logic should be supported all around.

Thanks
/lgtm
/approve

**Pull request merged**
