### PR TITLE
docs: make user more easily to build custom plugin

### PR DESCRIPTION
**Pull request by xiao-jay**
pr change
1、image name `volcano.sh/vc-scheduler:latest` is error ,correct is volcanosh/vc-scheduler:latest
2、build magic.so output to plugins/magic.so,because Dockerfile is `COPY plugins plugins`
3、add sample Dockerfile
@zen-xu

### CODE REVIEW

**Comment by xiao-jay** [comment]
@william-wang @k82cn @wangyang0616 Could you please review this pr?

**Review by hwdef — COMMENTED** [review]
/lgtm

**Review by william-wang — APPROVED** [review]
/approve

**Pull request merged**
