### PR TITLE
Add a link to the volcano official website

### PR DESCRIPTION
**Pull request by ChenglongGao327**
Easy to jump to the volcano official website

### CODE REVIEW

**Review by shinytang6 — CHANGES_REQUESTED** [review]
Thx for you contributions!
BTW, pls fix the DCO

**Comment by lowang-bh** [comment]
It is ok to me.

**Comment by Thor-wl** [comment]
/lgtm
Please fix the DCO

**Comment by ChenglongGao327** [comment]
> Please fix the DCO
done

**Review by shinytang6 — APPROVED** [review]
/lgtm
/approve

**Comment by ChenglongGao327** [comment]
> BTW, pls fix the DCO
done

**Review by Thor-wl — APPROVED** [review]

**Pull request merged**
