### PR TITLE
fix: exec job validate after init ssn.Tiers

### PR DESCRIPTION
**Pull request by liushaoxiong10**
`JobValid` is not executed when `openingSession`,  `ssn.Tiers` and `plugin.OnSessionOpen(ssn)` are after `openSession`, so `JobValid` should be moved after `plugin.OnSessionOpen(ssn)`

### CODE REVIEW

**Comment by liushaoxiong10** [comment]
@lowang-bh Hi, I saw your review on [pr 3087](https://github.com/volcano-sh/volcano/pull/3087), can you review it for me?

**Comment by lowang-bh** [comment]
Althrough it is same as former PR#3087, but the commiter of that pr is not active.

/lgtm

**Comment by liushaoxiong10** [comment]
> Althrough it is same as former PR #3087, but the commiter of that pr is not active.
> 
> /lgtm

thanks~

**Comment by liushaoxiong10** [comment]
@william-wang please review this pr，thanks

**Review by lowang-bh — APPROVED** [review]
/lgtm

**Comment by lowang-bh** [comment]
Hi，@liushaoxiong10 this pr has been revert due to the merge blocked the ci. Please commit a new one and fix the CI.

**Comment by liushaoxiong10** [comment]
> Hi，@liushaoxiong10 this pr has been revert due to the merge blocked the ci. Please commit a new one and fix the CI.

get, I'll take care of it.

**Pull request merged**
