### PR TITLE
fix some typos

### PR DESCRIPTION
**Pull request by halegreen**

### CODE REVIEW

**Comment by wangyang0616** [comment]
It's ok to me. 
Please help trigger CI. Thanks! @william-wang

**Review by Thor-wl — APPROVED** [review]

**Comment by halegreen** [comment]
@Thor-wl any problems?

**Review by shinytang6 — APPROVED** [review]
/approve

**Comment by halegreen** [comment]
@zen-xu hi, any problems?

**Comment by halegreen** [comment]
@zen-xu hi, any problems?

**Comment by halegreen** [comment]
@shinytang6 hi , can this be merged?

**Comment by lowang-bh** [comment]
LGTM

**Pull request merged**
