### PR TITLE
resolve unused variable warning

### PR DESCRIPTION
**Pull request by lowang-bh**

### CODE REVIEW

**Review by hwdef — COMMENTED** [review]
please fix the CI

**Comment by lowang-bh** [comment]
> please fix the CI

How to make it re-run? CI log is failed to install golangci-lint.
```sh
hack/verify-golangci-lint.sh
checking whether golangci-lint has been installed
installing golangci-lint .
golangci/golangci-lint info checking GitHub for tag 'v1.50.0'
golangci/golangci-lint crit unable to find 'v1.50.0' - use 'latest' or see https://github.com/golangci/golangci-lint/releases for details
make: *** [Makefile:[15](https://github.com/volcano-sh/volcano/actions/runs/5092541338/jobs/9154015872?pr=2864#step:5:16)3: lint] Error 1
golangci-lint installed failed, exiting.
Error: Process completed with exit code 2.
```

**Comment by hwdef** [comment]
you can close and reopen your pr

**Comment by lowang-bh** [comment]
trigger CI

**Review by hwdef — COMMENTED** [review]
/lgtm

**Review by hzxuzhonghu — APPROVED** [review]

**Pull request merged**
