### PR TITLE
Added crd conversion.

### LINKED ISSUE #595: Avoid version conversion cross the components
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**:

For now, we did version conversion by hard code cross different components in the project, which makes it hard to maintain; it's better to leverage crd versioning feature to do that. Refer to the following link on how to do that: https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/ .

### PR DESCRIPTION
**Pull request by k82cn**
Signed-off-by: Klaus Ma <klaus1982.cn@gmail.com>

fixed #595 

```release note
Add CRD conversion webhook to avoid version checking in different components.
```

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
Is this the implementation of native k8s crd conversion? It means a client can get a resource(queue, podgroup, etc )of any version, and the conversion is auto done.

**Comment by k82cn** [comment]
@hzxuzhonghu refer to https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/

**Comment by hzxuzhonghu** [comment]
What i am asking is if you implemented this? I donot think you can do that natively, at least for volcano the group of the resources changed.

**Comment by k82cn** [comment]
> What i am asking is if you implemented this?

yes

**Pull request closed without merging**
