### PR TITLE
Add task index

### PR DESCRIPTION
**Pull request by lowang-bh**
add a index for each replica of different task spec/role in pod, like kubeflow's tf/pytorch

https://github.com/kubeflow/training-operator/blob/3107ab73bb5334e8736b88320e97069b1bc40f3e/pkg/apis/kubeflow.org/v1/common_types.go#L23-L38
```go
const (
        // ReplicaIndexLabel represents the label key for the replica-index, e.g. 0, 1, 2.. etc
        ReplicaIndexLabel = "training.kubeflow.org/replica-index"


        // ReplicaTypeLabel represents the label key for the replica-type, e.g. ps, worker etc.
        ReplicaTypeLabel = "training.kubeflow.org/replica-type"
)
```

relative issue at [how to create a service for every task pod #2654](https://github.com/volcano-sh/volcano/issues/2654)

Note: please merge [add task index key for pod in annotation/label #114](https://github.com/volcano-sh/apis/pull/114) first. And then I will replace the dependency in the second commit with that commit id.

### CODE REVIEW

**Review by hwdef — COMMENTED** [review]
/lgtm

**Comment by william-wang** [comment]
please refresh the go.mod

**Comment by lowang-bh** [comment]
> please refresh the go.mod

Updated.

**Comment by lowang-bh** [comment]
Hi, @william-wang , [add task index key for pod in annotation/label](https://github.com/volcano-sh/apis/pull/114) has merged in apis. So this PR is ready to be merged now.

**Review by william-wang — APPROVED** [review]
/lgtm

**Pull request merged**
