### PR TITLE
fix: log format param missing

### PR DESCRIPTION
**Pull request by lowang-bh**
klog.Errorf miss format param

### CODE REVIEW

**Comment by lowang-bh** [comment]
@wangyang0616 @Thor-wl @william-wang Please take a look at this little fix. thanks

**Comment by wangyang0616** [comment]
It's ok to me, please have a look. Thanks! @jiangkaihua @william-wang

**Review by hwdef — COMMENTED** [review]
/lgtm

**Review by Thor-wl — APPROVED** [review]

**Pull request merged**
