### PR TITLE
generate crds using kubebuilder

### PR DESCRIPTION
**Pull request by stpabhi**
Generate CRDs using controller-gen and kubebuilder annotations.

### CODE REVIEW

**Comment by k82cn** [comment]
/approve

That's great to have such a PR! Let's get it merged when CI happy :)

**Comment by hzxuzhonghu** [comment]
Awesome @stpabhi

**Comment by hzxuzhonghu** [comment]
fix: https://github.com/volcano-sh/volcano/issues/809

**Comment by stpabhi** [comment]
@k82cn Thank you. Travis is very much happy now. :) Could you approve?

**Pull request merged**
