### PR TITLE
refactor(e2e): separate utils as a single package

### PR DESCRIPTION
**Pull request by rudeigerc**
Signed-off-by: rudeigerc <rudeigerc@gmail.com>

Related to #1284 

Currently, the utilities of e2e test suites are embedded in each suite, which is inappropriate for maintenance and development.

This pull request separates the utilities and `vcctl` related tests as single packages.

```shell
$ tree test/e2e
test/e2e
├── jobp
├── jobseq
├── schedulingaction
├── schedulingbase
├── util
│   ├── job.go
│   ├── node.go
│   ├── podgroup.go
│   ├── queue.go
│   ├── replicaset.go
│   └── util.go
└── vcctl
    ├── cli_util.go
    ├── command.go
    ├── e2e_test.go
    ├── main_test.go
    └── vcctl.go
```

### CODE REVIEW

**Comment by shinytang6** [comment]
l am ok to the code structure :)
LGTM overall.

**Review by shinytang6 — APPROVED** [review]

**Comment by Thor-wl** [comment]
LGTM, too. 
/lgtm
/approve

**Comment by Thor-wl** [comment]
It seems that timeout occurs frequently recently as to the e2e runs in github action machines. Can you help for that? @rudeigerc

**Comment by rudeigerc** [comment]
@Thor-wl Sure. I will take a look at it.

**Pull request merged**
