### PR TITLE
Tune default weights for nodeOrder plugin

### PR DESCRIPTION
**Pull request by kerthcet**
Signed-off-by: kerthcet <kerthcet@gmail.com>

fix: https://github.com/volcano-sh/volcano/issues/2452

### CODE REVIEW

**Comment by kerthcet** [comment]
@hzxuzhonghu Can you help to review this? This PR helps to make the scheduling decisions more reasonable.

**Comment by william-wang** [comment]
Thanks for your pr. please make the ci happy.

**Comment by kerthcet** [comment]
> Thanks for your pr. please make the ci happy.

I think the CI is broken, all my prs are all failed. And I think I'm not a trust contributor now, but let me have a try.

/ok-to-test
/retest

**Comment by kerthcet** [comment]
Some errors: `flag provided but not defined: -ginkgo.grace-period`

**Comment by kerthcet** [comment]
> Thanks for your pr. please make the ci happy.

CI is fixed now.

**Comment by kerthcet** [comment]
Rebased.

**Review by hzxuzhonghu — COMMENTED** [review]
/lgtm

The ci is still failing

**Comment by kerthcet** [comment]
> The ci is still failing

Thanks for responding, I think this is fixed by another PR https://github.com/volcano-sh/volcano/pull/2548, no one seems to have time in reviewing. @hzxuzhonghu

**Comment by kerthcet** [comment]
Rebased @hzxuzhonghu

**Comment by kerthcet** [comment]
cc @hzxuzhonghu @william-wang

**Comment by william-wang** [comment]
@kerthcet Thanks for your pr. The update make sense.

**Review by william-wang — APPROVED** [review]
/lgtm

**Review by Thor-wl — APPROVED** [review]

**Comment by jiangkaihua** [comment]
/lgtm

It is reasonable that Volcano kept the same dedault weight as kube-scheduler. like: https://github.com/kubernetes/kubernetes/blob/3742d14998fc41dd8c086e8d44cf6b50023c831e/pkg/scheduler/apis/config/v1/default_plugins.go#L33-L54

**Comment by Thor-wl** [comment]
@kerthcet Can you rebase the PR to the latest master branch code for this private branch is out of date? I'll try to merge it. Thanks!

**Comment by kerthcet** [comment]
> @kerthcet Can you rebase the PR to the latest master branch code for this private branch is out of date? I'll try to merge it. Thanks!

Done

**Review by Thor-wl — APPROVED** [review]

**Comment by kerthcet** [comment]
Rebased again @Thor-wl

**Review by Thor-wl — APPROVED** [review]
/lgtm

**Pull request merged**
