### PR TITLE
doc: add local debug method for scheduler

### PR DESCRIPTION
**Pull request by wang-mask**
Doc: add the debug doc for volcano scheduler locally

### CODE REVIEW

**Comment by wang-mask** [comment]
The method for debugging controllers is like the method of shcduler. The method for debugging webhook is a little complicated, you can refer to [this doc](https://github.com/fluid-cloudnative/fluid/blob/master/docs/zh/dev/how_to_develop.md#%E8%B0%83%E8%AF%95webhook%E7%BB%84%E4%BB%B6) .

**Comment by lowang-bh** [comment]
I think this is a basic skill which developer should has. It has little relationship with volcano.

**Comment by hwdef** [comment]
> I think this is a basic skill which developer should has. It has little relationship with volcano.
> 
> @wangyang0616 @hwdef please have a look. thanks.

Agree, but I'm not against merging this PR.

**Comment by wang-mask** [comment]
> I think this is a basic skill which developer should has. It has little relationship with volcano.
> 
> @wangyang0616 @hwdef please have a look. thanks.

Although this is basic, it is important and necessary for beginners for volcano. And it is supplied by many open source projects.

**Pull request closed without merging**
