### PR TITLE
Boilerplate update

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
Remove `YEAR`, keep the ci valid in a new year.

### CODE REVIEW

**Comment by TommyLike** [comment]
Which is failing?

**Comment by hzxuzhonghu** [comment]
same things have happened in k8s, like when time goes to 2020.1.1, the verify will fail.

**Comment by TommyLike** [comment]
They should fix it:)

**Comment by k82cn** [comment]
let keep "YEAR" there.

**Pull request closed without merging**
