### PR TITLE
fix: not skip lower prioprity job when job with high priority allocated failed

### PR DESCRIPTION
**Pull request by merryzhou**
fix https://github.com/volcano-sh/volcano/issues/1086

### CODE REVIEW

**Review by Thor-wl — COMMENTED** [review]
/lgtm

**Comment by Thor-wl** [comment]
@william-wang This fix should be merge to v1.0&v0.4

**Comment by william-wang** [comment]
The fix might impact current users. For example, there is one high priority big job. 
This kind of job might starve if there is continous small low priority job comming.

**Comment by Thor-wl** [comment]
> The fix might impact current users. For example, there is one high priority big job.
> This kind of job might starve if there is continous small low priority job comming.

IC, but i think it should not be a default managerment process for most users may expect the usage rate and throughput of cluster is as high as possible. That resource reservation requirement is satisfied with specific actions and plugins may be a better solution. https://github.com/volcano-sh/volcano/pull/1044 is working for this.

**Pull request merged**
