### PR TITLE
pod admission  mutate patch affinity

### PR DESCRIPTION
**Pull request by jiamin13579**
Admission pods, resourceGroups support mutate patch pod affinity. The format is a json string.

volcano-admission.conf example
```yaml
apiVersion: v1
data:
  volcano-admission.conf: |
    resourceGroups:
    - resourceGroup: fixed                        # if the object is unsetted, default is:  the key is annotation,
      schedulerName: volcano                      # the annotation key is fixed and is "volcano.sh/resource-group", The corresponding value is the resourceGroup field
      object:
        key: annotation
        value:
        - "volcano.sh/resource-group-job-role: master"
      # set the affinity for patching, the format is a json string.
      affinity: "{\"nodeAffinity\":{\"requiredDuringSchedulingIgnoredDuringExecution\":{\"nodeSelectorTerms\":[{\"matchExpressions\":[{\"key\":\"volcano.sh/nodetype",\"operator\":\"In\",\"values\":[\"fixed\"]}]}]}}}"
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: volcano
    meta.helm.sh/release-namespace: volcano-system
  labels:
    app.kubernetes.io/managed-by: Helm
  name: volcano-admission-configmap
  namespace: volcano-system
```

### CODE REVIEW

**Review by hwdef — COMMENTED** [review]
What is the background of this function

**Comment by jiamin13579** [comment]
> What is the background of this function

We want to use more rich affinity configurations to control pod allocation, which may not only be node selection. In case of insufficient machines, we can occupy cluster resources of other services.

**Comment by hwdef** [comment]
Sorry I still don't understand the scenario, please be more specific or give an example, thanks

**Review by hwdef — COMMENTED** [review]
/lgtm

**Comment by william-wang** [comment]
I just restarted the ci.

**Review by william-wang — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
