### PR TITLE
fix volcano-admission restart error, failed calling webhook "mutatepod.volcano.sh"

### PR DESCRIPTION
**Pull request by nature1995**
See the issue: https://github.com/volcano-sh/volcano/issues/2610

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
I am not sure i understand why this could fix

**Comment by hzxuzhonghu** [comment]
I missed why added namespace selector to webhookconfiguration in https://github.com/volcano-sh/volcano/pull/2346/files#diff-3030d9b087818e1e5ce1ad6b18099ec623c1b517c0999800d62a903d2990d778

**Comment by nature1995** [comment]
> I missed why added namespace selector to webhookconfiguration in https://github.com/volcano-sh/volcano/pull/2346/files#diff-3030d9b087818e1e5ce1ad6b18099ec623c1b517c0999800d62a903d2990d778

I think th namespaceSelector is use for control webhook scope. If we do not add the label on namespace, the pod create operation alse need to access the webhook. Then, you will see the pod restart error.

**Comment by hwdef** [comment]
I think this may be caused by your k8s version being too low. The ns in the k8s cluster of the lower version may not have this label.

I check this in kubernetes 1.25, an I found this lable.

image


So not sure if your patch should be submitted to the master branch, maybe it should be submitted to other lower version branches

**Comment by nature1995** [comment]
> I think this may be caused by your k8s version being too low. The ns in the k8s cluster of the lower version may not have this label.
> 
> I check this in kubernetes 1.25, an I found this lable.
> 
> image
> 
> So not sure if your patch should be submitted to the master branch, maybe it should be submitted to other lower version branches

We use lower k8s version in most of production enviroment. I think we need add the labels in the yaml when create the namespace compatible with most k8s version.

**Comment by hwdef** [comment]
sounds reasonable, please make CI happy.

**Comment by nature1995** [comment]
Could you help me to restart the CI action?

**Comment by nature1995** [comment]
> sounds reasonable, please make CI happy.

**Comment by nature1995** [comment]
> sounds reasonable, please make CI happy.
Could you see what happen for the CI？ The status is still waiting for approved.

**Comment by hwdef** [comment]
> > sounds reasonable, please make CI happy.
> 
> Could you see what happen for the CI？ The status is still waiting for approved.

I think I do not have the permission to run CI,please find some other maintainers.

**Comment by nature1995** [comment]
@hzxuzhonghu Do you have the permission to rerun the CI test?

**Comment by hzxuzhonghu** [comment]
Sorry, i cannot.

**Comment by nature1995** [comment]
The last task is mark lgtm labels. @volcano-sh-bot @hzxuzhonghu @qiankunli

**Review by hwdef — COMMENTED** [review]
/lgtm

**Comment by nature1995** [comment]
> /lgtm

also need approve label.

**Comment by hwdef** [comment]
> > /lgtm
> 
> also need /approved label.

An approver can only add one kind of tag

**Comment by hwdef** [comment]
/assign @shinytang6 
This PR solves a problem we talked about before.

**Comment by hzxuzhonghu** [comment]
@hwdef  sorry i forgot to approve

**Comment by hwdef** [comment]
> What about installing volcano by helm?

I guess this problem still exists when installing with helm.🤔

**Pull request merged**
