### PR TITLE
fix issue that sa has no permit of leases when elect leader and enable leader elect by default

### LINKED ISSUE #2825: Volcano multi-copy deployment does not enable master election by default
**What happened**:
Deploying Volcano in the form of multiple copies, the vc-controller and vc-scheduler components do not enable the master selection function by default, and multiple vc-schedulers work at the same time, there may be a problem that the scheduled pod fails to pull up on the node node, such as encountering ' ouf of cpu' and other errors.

**What you expected to happen**:
The master election function is enabled by default, and only one scheduler works in the case of multi-copy deployment. 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version: master
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### LINKED ISSUE #2872: service account has no permit to access lease when enable leader elect
**What happened**:

```sh
E0527 06:15:36.041286       1 leaderelection.go:330] error retrieving resource lock volcano-system/volcano: leases.coordination.k8s.io "volcano" is forbidden: User "system:serviceaccount:volcano-system:volcano-scheduler" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "volcano-system"
E0527 06:15:41.445378       1 leaderelection.go:330] error retrieving resource lock volcano-system/volcano: leases.coordination.k8s.io "volcano" is forbidden: User "system:serviceaccount:volcano-system:volcano-scheduler" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "volcano-system"
E0527 06:15:47.393144       1 leaderelection.go:330] error retrieving resource lock volcano-system/volcano: leases.coordination.k8s.io "volcano" is forbidden: User "system:serviceaccount:volcano-system:volcano-scheduler" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "volcano-system"
E0527 06:15:52.987215       1 leaderelection.go:330] error retrieving resource lock volcano-system/volcano: leases.coordination.k8s.io "volcano" is forbidden: User "system:serviceaccount:volcano-system:volcano-scheduler" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "volcano-system"
```

**What you expected to happen**:

no error and get lease successfully

**How to reproduce it (as minimally and precisely as possible)**:

start up with leader-elect enabled 
```yaml
     - --leader-elect=true
     - --lock-object-namespace=volcano-system
```

**Anything else we need to know?**:

both scheduler and controller

**Environment**:
- Volcano Version: master branch
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by lowang-bh**
fix #2825 default to enable leader-elect
fix #2872 about sa has no permit of lease

### CODE REVIEW

**Review by william-wang — APPROVED** [review]
/lgtm
/approve

**Review by william-wang — APPROVED** [review]
/lgtm
/approve

**Comment by wangyang0616** [comment]
I think the configuration of `LockObjectNamespace` needs to be dynamically specified in the startup command in addition to setting the default value, because when the user installs Volcano through helm, the specified namespace is not necessarily volcano-system, and there is no volcano-system in the system at this time namespace, the startup will report an error, such as the CI error should be caused by this reason.

**Comment by lowang-bh** [comment]
specify `--lock-object-namespace` in helm chat. Also `--lock-object-namespace=volcano-system` is set as default in volcano scheduler/controller deployment.

Following shows `helm install volcano helm/chart/volcano --namespace volcano-test`
image

image

**Review by hwdef — COMMENTED** [review]
/lgtm

**Comment by hwdef** [comment]
please rebase your code

**Comment by lowang-bh** [comment]
> please rebase your code

Done.

**Comment by hwdef** [comment]
please fix the CI

**Comment by lowang-bh** [comment]
To do: need resolve
```sh
E0527 06:15:36.041286       1 leaderelection.go:330] error retrieving resource lock volcano-system/volcano: leases.coordination.k8s.io "volcano" is forbidden: User "system:serviceaccount:volcano-system:volcano-scheduler" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "volcano-system"
E0527 06:15:41.445378       1 leaderelection.go:330] error retrieving resource lock volcano-system/volcano: leases.coordination.k8s.io "volcano" is forbidden: User "system:serviceaccount:volcano-system:volcano-scheduler" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "volcano-system"
E0527 06:15:47.393144       1 leaderelection.go:330] error retrieving resource lock volcano-system/volcano: leases.coordination.k8s.io "volcano" is forbidden: User "system:serviceaccount:volcano-system:volcano-scheduler" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "volcano-system"
E0527 06:15:52.987215       1 leaderelection.go:330] error retrieving resource lock volcano-system/volcano: leases.coordination.k8s.io "volcano" is forbidden: User "system:serviceaccount:volcano-system:volcano-scheduler" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "volcano-system"
```

**Comment by lowang-bh** [comment]
> To do: need resolve
> 
> ```shell
> E0527 06:15:36.041286       1 leaderelection.go:330] error retrieving resource lock volcano-system/volcano: leases.coordination.k8s.io "volcano" is forbidden: User "system:serviceaccount:volcano-system:volcano-scheduler" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "volcano-system"
> E0527 06:15:41.445378       1 leaderelection.go:330] error retrieving resource lock volcano-system/volcano: leases.coordination.k8s.io "volcano" is forbidden: User "system:serviceaccount:volcano-system:volcano-scheduler" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "volcano-system"
> E0527 06:15:47.393144       1 leaderelection.go:330] error retrieving resource lock volcano-system/volcano: leases.coordination.k8s.io "volcano" is forbidden: User "system:serviceaccount:volcano-system:volcano-scheduler" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "volcano-system"
> E0527 06:15:52.987215       1 leaderelection.go:330] error retrieving resource lock volcano-system/volcano: leases.coordination.k8s.io "volcano" is forbidden: User "system:serviceaccount:volcano-system:volcano-scheduler" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "volcano-system"
> ```
Have fixed.

**Review by hwdef — COMMENTED** [review]
/lgtm

**Pull request merged**
