### PR TITLE
Automatically generate yaml files for arm64

### PR DESCRIPTION
**Pull request by hwdef**
fix: #2010

### CODE REVIEW

**Comment by Yikun** [comment]
@hwdef Does it works as expected? If ready to review, I can help to validate, feel free to ping me when it is ready.

**Comment by william-wang** [comment]
@hwdef , Thanks for the pr. It is important. please help to make the CI happy :)

**Comment by Yikun** [comment]
```
spark@yikun-arm:~$ kubectl apply -f https://raw.githubusercontent.com/volcano-sh/volcano/release-1.3/installer/volcano-development-arm64.yaml
namespace/volcano-system created
configmap/volcano-scheduler-configmap created
serviceaccount/volcano-scheduler created
clusterrole.rbac.authorization.k8s.io/volcano-scheduler created
clusterrolebinding.rbac.authorization.k8s.io/volcano-scheduler-role created
deployment.apps/volcano-scheduler created
serviceaccount/volcano-admission created
clusterrole.rbac.authorization.k8s.io/volcano-admission created
clusterrolebinding.rbac.authorization.k8s.io/volcano-admission-role created
deployment.apps/volcano-admission created
service/volcano-admission-service created
job.batch/volcano-admission-init created
serviceaccount/volcano-controllers created
clusterrole.rbac.authorization.k8s.io/volcano-controllers created
clusterrolebinding.rbac.authorization.k8s.io/volcano-controllers-role created
deployment.apps/volcano-controllers created
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
customresourcedefinition.apiextensions.k8s.io/jobs.batch.volcano.sh created
customresourcedefinition.apiextensions.k8s.io/commands.bus.volcano.sh created
customresourcedefinition.apiextensions.k8s.io/podgroups.scheduling.volcano.sh created
customresourcedefinition.apiextensions.k8s.io/queues.scheduling.volcano.sh created
```

**Comment by Yikun** [comment]
```
$ kubectl apply -f https://raw.githubusercontent.com/volcano-sh/volcano/7bc3ffa350675a2c26f392df7e141511e0ba81d3/installer/volcano-development-arm64.yaml
namespace/volcano-system created
namespace/volcano-monitoring created
serviceaccount/volcano-admission created
configmap/volcano-admission-configmap created
clusterrole.rbac.authorization.k8s.io/volcano-admission created
clusterrolebinding.rbac.authorization.k8s.io/volcano-admission-role created
service/volcano-admission-service created
deployment.apps/volcano-admission created
job.batch/volcano-admission-init created
customresourcedefinition.apiextensions.k8s.io/jobs.batch.volcano.sh created
customresourcedefinition.apiextensions.k8s.io/commands.bus.volcano.sh created
serviceaccount/volcano-controllers created
clusterrole.rbac.authorization.k8s.io/volcano-controllers created
clusterrolebinding.rbac.authorization.k8s.io/volcano-controllers-role created
deployment.apps/volcano-controllers created
serviceaccount/volcano-scheduler created
configmap/volcano-scheduler-configmap created
clusterrole.rbac.authorization.k8s.io/volcano-scheduler created
clusterrolebinding.rbac.authorization.k8s.io/volcano-scheduler-role created
service/volcano-scheduler-service created
deployment.apps/volcano-scheduler created
customresourcedefinition.apiextensions.k8s.io/podgroups.scheduling.volcano.sh created
customresourcedefinition.apiextensions.k8s.io/queues.scheduling.volcano.sh created
customresourcedefinition.apiextensions.k8s.io/numatopologies.nodeinfo.volcano.sh created

$ kubectl get po -A
NAMESPACE        NAME                                   READY   STATUS      RESTARTS   AGE
kube-system      coredns-74ff55c5b-jrmpf                1/1     Running     0          3h50m
kube-system      etcd-minikube                          1/1     Running     0          3h50m
kube-system      kube-apiserver-minikube                1/1     Running     0          3h50m
kube-system      kube-controller-manager-minikube       1/1     Running     0          3h50m
kube-system      kube-proxy-x5wqt                       1/1     Running     0          3h50m
kube-system      kube-scheduler-minikube                1/1     Running     0          3h50m
kube-system      storage-provisioner                    1/1     Running     1          3h50m
volcano-system   volcano-admission-54b4798bff-bnnkf     0/1     Error       2          31s
volcano-system   volcano-admission-init-sxkmj           0/1     Completed   0          31s
volcano-system   volcano-controllers-865f496899-bg4cm   0/1     Error       2          31s
volcano-system   volcano-scheduler-5f8844cd99-dscdb     0/1     Error       2          31s
```

**Comment by hwdef** [comment]
Please check the log of volcano-admission-init-sxkmj

**Comment by Yikun** [comment]
```
$ kubectl logs volcano-admission-init-ljsnd -n volcano-system
creating certs in dir /tmp
Generating RSA private key, 2048 bit long modulus (2 primes)
...............................................................+++++
............................................................................+++++
e is 65537 (0x010001)
Generating RSA private key, 2048 bit long modulus (2 primes)
.....................+++++
.............................+++++
e is 65537 (0x010001)
Signature ok
subject=CN = volcano-admission-service.volcano-system.svc
Getting CA Private Key
secret/volcano-admission-secret created
```

**Comment by Yikun** [comment]
oh, maybe it's the images outdate issue

**Comment by hwdef** [comment]
> oh, maybe it's the images outdate issue, images pulls from dockerhub.

yes, it seems that the mirror image of arm64 is not automatically pushed every day

**Comment by hwdef** [comment]
@william-wang @Thor-wl 

Can you help fix the images push bot?

**Review by Yikun — APPROVED** [review]

**Review by william-wang — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
