### PR TITLE
fix jobflow CRD metadata.annotations: Too long error

### PR DESCRIPTION
**Pull request by guoqinwill**
fix jobflow CRD metadata.annotations: Too long error。
It is caused after https://github.com/volcano-sh/volcano/pull/3295  ，this modification refers to https://github.com/volcano-sh/volcano/pull/3197

### CODE REVIEW

**Comment by lowang-bh** [comment]
I remember this is fixed in #3197

**Comment by Monokaix** [comment]
> I remember this is fixed in #3197

That pr fixed vcjob, here we fixed the jobflow resource.

**Review by hwdef — COMMENTED** [review]
/lgtm

**Review by hzxuzhonghu — COMMENTED** [review]
LGTM，just wondering what is the length limit

**Comment by guoqinwill** [comment]
> LGTM，just wondering what is the length limit

may be like this:https://github.com/volcano-sh/volcano/issues/3107

**Review by lowang-bh — APPROVED** [review]
/lgtm

**Review by hzxuzhonghu — APPROVED** [review]

**Pull request merged**
