### PR TITLE
Add MaxRequeueNum as a controller-manager param

### LINKED ISSUE #1031: Add maxRetries parameters to controller
/kind feature

**What happened**:

```
const (
	// maxRetries is the number of times a volcano job will be retried before it is dropped out of the queue.
	// With the current rate-limiter in use (5ms*2^(maxRetries-1)) the following numbers represent the times
	// a volcano job is going to be requeued:
	//
	// 5ms, 10ms, 20ms, 40ms, 80ms, 160ms, 320ms, 640ms, 1.3s, 2.6s, 5.1s, 10.2s, 20.4s, 41s, 82s
	maxRetries = 15
)
```

the maxRetries is hard coded.

And In my scenario, I hope the job controller keep retrying, just like other k8s controllers.

So, is it ok to add  a maxRetries parameter, default value is 15, when set to -1, it means retry endlessly

**Environment**:
- Volcano Version: v1.0.1

### PR DESCRIPTION
**Pull request by shinytang6**
resolves #1031 
Signed-off-by: tangliang <1074461480@qq.com>

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
It seems you need to rebase and so that the new travis config from #1085 can take effect

**Comment by shinytang6** [comment]
> It seems you need to rebase and so that the new travis config from #1085 can take effect

Sure, but because of the problem reported here #1076, it is very difficult for me to synchronize upstream with my local master, I have to fork the project again, so please refer to #1087 and merge that one :)

**Pull request closed without merging**
