### PR TITLE
Added default namespace env for other CLIs - vcancel, vjobs, vresume, vsuspend

### PR DESCRIPTION
**Pull request by thandayuthapani**
xref https://github.com/volcano-sh/volcano/issues/700

### CODE REVIEW

**Comment by k82cn** [comment]
let's build a util function for that as Namespace is a common parameter for CLIs.

**Comment by hzxuzhonghu** [comment]
What happens when we leave it to empty? From my understanding, it works as `default`. If so, why do we need this?

**Comment by thandayuthapani** [comment]
> let's build a util function for that as Namespace is a common parameter for CLIs.

Flag struct variable and struct are not exposed, so creating a util function to handle all those struct will be a problem.

**Comment by k82cn** [comment]
> Flag struct variable and struct are not exposed, so creating a util function to handle all those struct will be a problem.

Let's add struct such as `JobCommonFlags` :)

**Pull request closed without merging**
