### PR TITLE
add task status named ReleasingFailed

### PR DESCRIPTION
**Pull request by ycfnana**
the question is https://github.com/volcano-sh/volcano/pull/2922
I met a problem, pod always be Pending when one node has zombie pod and another node has enough reource, due to the relaesing status, I think waiting time larger than TerminationGracePeriodSeconds it should not be releaseing, may happen something error, its should be another status like ReleasingFailed

### CODE REVIEW

**Comment by lowang-bh** [comment]
Thanks for your contributions!
This is a great change and will have a large effect.
Would you please provide those informations?
1. the necessary ut tests.
2. the scenario what happens without the change, and the result with this fix.

**Comment by ycfnana** [comment]
> Thanks for your contributions! This is a great change and will have a large effect. Would you please provide those informations?
> 
> 1. the necessary ut tests.
> 2. the scenario what happens without the change, and the result with this fix.




> progress

**Comment by ycfnana** [comment]
> Thanks for your contributions! This is a great change and will have a large effect. Would you please provide those informations?
> 
> 1. the necessary ut tests.
> 2. the scenario what happens without the change, and the result with this fix.


Thanks, I'll  add ut test next week.
I have an issue, there are enough resource both in nodeA and nodeB.  PodB in nodeB has been deleted,  but the status is still "Terminating" due to the zombie progress.
In the time,  add the new job named  JobC with PodD, it can be scheduled in nodeA, but status of podD is Pending. From its log, I find status of JobC is "Pipelined", waiting nodeB to releasing podB. But podB has something wrong like "ReleasingFailed". 
So I want to fix this condition.

**Comment by ycfnana** [comment]
> Thanks for your contributions! This is a great change and will have a large effect. Would you please provide those informations?
> 
> 1. the necessary ut tests.
> 2. the scenario what happens without the change, and the result with this fix.

can you help review it again?

**Comment by lowang-bh** [comment]
> > Thanks for your contributions! This is a great change and will have a large effect. Would you please provide those informations?
> > 
> > 1. the necessary ut tests.
> > 2. the scenario what happens without the change, and the result with this fix.
> 
> can you help review it again?

It is clear to me now. Just a little comment, please have a look at the review comment. Thanks.

**Comment by ycfnana** [comment]
/assign @wangyang0616 @william-wang @huone1 
can somebody help review it

**Comment by wangyang0616** [comment]
Can this pr [#2815](https://github.com/volcano-sh/volcano/pull/2815) fix your problem.

**Comment by Thor-wl** [comment]
@ycfnana Thanks for your report. Personally speaking, I think the root reason is something goes wrong with the unexpected pod status instead of task's status. There is no enough resource to start new pods, which belong to the pipelined jobs. So I don't get the point why should add a task status and what this can help for users.
/hold

**Comment by ycfnana** [comment]
> @ycfnana Thanks for your report. Personally speaking, I think the root reason is something goes wrong with the unexpected pod status instead of task's status. There is no enough resource to start new pods, which belong to the pipelined jobs. So I don't get the point why should add a task status and what this can help for users. /hold

thanks,  sometimes pod status is pending even if there are enough resources to start a new pod because of  unexpected pod status, you can see my comment in my ut code. But this pr https://github.com/volcano-sh/volcano/pull/2815 may solve my problem. I'll close this pr if test it's ok

**Pull request closed without merging**
