### PR TITLE
Ignore error from deleteTask

### PR DESCRIPTION
**Pull request by zionwu**
Fix the same issue described in https://github.com/kubernetes-sigs/kube-batch/issues/931

### CODE REVIEW

**Comment by k82cn** [comment]
please help to make ci happy :)

**Comment by hzxuzhonghu** [comment]
/lgtm

Curious about the deep cause

**Comment by hzxuzhonghu** [comment]
e2e flake

**Comment by zionwu** [comment]
@hzxuzhonghu the cause is described in detail in this issue https://github.com/kubernetes-sigs/kube-batch/issues/931. 

@k82cn the CI job https://travis-ci.com/github/volcano-sh/volcano/builds/159536689 already pass the `E2E Tests` but it is cancelled at `Publish Release`.  I re-push the commit to trigger a new CI job.

**Comment by hzxuzhonghu** [comment]
I find the error is weird, the namespace `test` is being deleted when a newer test is run.

But we have code prevent that
```
func cleanupTestContext(ctx *context) {
	foreground := metav1.DeletePropagationForeground
	err := ctx.kubeclient.CoreV1().Namespaces().Delete(ctx.namespace, &metav1.DeleteOptions{
		PropagationPolicy: &foreground,
	})
	Expect(err).NotTo(HaveOccurred())

	deleteQueues(ctx)

	deletePriorityClasses(ctx)

	// Wait for namespace deleted.
	err = wait.Poll(100*time.Millisecond, twoMinute, namespaceNotExist(ctx))
	Expect(err).NotTo(HaveOccurred())
}
```

**Pull request merged**
