### PR TITLE
Propose TommyLike as reviewers and approvers of controller packages

### PR DESCRIPTION
**Pull request by TommyLike**
1. Feature and BugFix related PRs status: https://github.com/volcano-sh/volcano/graphs/contributors
2. Help reviews on most of the maintain and feature related PRS on job controller management field.

### CODE REVIEW

**Comment by k82cn** [comment]
please help to append your contribution, e.g. PRs, review comments.

**Comment by TommyLike** [comment]
> please help to append your contribution, e.g. PRs, review comments.

Done

**Comment by kevin-wangzefeng** [comment]
The recommaned way to do is listing the major contributions you have done here e.g. features authored/reviewed, bugs authored/reviewed etc.

**Comment by k82cn** [comment]
/lgtm
/approve

Thanks very much for your contribution !!

**Pull request merged**
