### PR TITLE
job event optimize

### PR DESCRIPTION
**Pull request by mikechengwei**
### What problem does this PR solve? 
#1094 

When podgroup recorder event,job also recorder.
### What is changed and how does it work?
When podgroup recorder event,job also recorder.

### CODE REVIEW

**Comment by Thor-wl** [comment]
@mikechengwei please close and reopen this PR to make CI happy

**Comment by Thor-wl** [comment]
CI timeout,  please close and reopen this PR

**Comment by mikechengwei** [comment]
@k82cn PLTA ,thanks

**Comment by mikechengwei** [comment]
@hzxuzhonghu @Thor-wl PTAL.

**Pull request merged**
