### PR TITLE
fix error during daily release

### PR DESCRIPTION
**Pull request by hwdef**
Signed-off-by: hwdef <hwdefcom@outlook.com>

fix: https://github.com/volcano-sh/volcano/pull/2435#issuecomment-1219028244

### CODE REVIEW

**Comment by hwdef** [comment]
well, I think CI errors have nothing to do with the change of this PR

**Review by shinytang6 — APPROVED** [review]
/approve

**Review by Thor-wl — APPROVED** [review]

**Comment by hwdef** [comment]
https://github.com/volcano-sh/volcano/runs/7898219193?check_suite_focus=true

The daily release still fails, and the error needs to continue to be resolved

**Comment by shinytang6** [comment]
> https://github.com/volcano-sh/volcano/runs/7898219193?check_suite_focus=true

Seems that we don't need `./hack/publish.sh` to upload images any more?

**Comment by hwdef** [comment]
> > https://github.com/volcano-sh/volcano/runs/7898219193?check_suite_focus=true
> 
> Seems that we don't need `./hack/publish.sh` to upload images any more?

yes, and we also do not need `./hack/publish.sh` to copy binary.

**Pull request merged**
