### PR TITLE
parse job min member info

### PR DESCRIPTION
**Pull request by lowang-bh**
split from #3057 (commit-1st: refact jobinfo's calculation to a function)

### CODE REVIEW

**Comment by Monokaix** [comment]
Why would we split it?

**Review by Thor-wl — COMMENTED** [review]
May I ask why do we put this piece of code out of the main function? Personally speaking, it is short and readable enough.

**Comment by lowang-bh** [comment]
> May I ask why do we put this piece of code out of the main function? Personally speaking, it is short and readable enough.

This is part of function to calculate job min resource (PR #3057). To let calculation function looks more compact.

But that PR seems can not be merged in few years, so I split the first small pr out. @Monokaix

**Comment by Monokaix** [comment]
> > May I ask why do we put this piece of code out of the main function? Personally speaking, it is short and readable enough.
> 
> This is part of function to calculate job min resource (PR #3057). To let calculation function looks more compact.
> 
> But that PR seems can not be merged in few years, so I split the first small commit out. @Monokaix

I think we can concern the original pr directly: )

**Pull request closed without merging**
