### PR TITLE
add ut converage report for v1.4.0

### PR DESCRIPTION
**Pull request by Thor-wl**
Signed-off-by: Thor-wl <13164644535@163.com>

### CODE REVIEW

**Review by shinytang6 — CHANGES_REQUESTED** [review]
where does this file come from?

**Review by william-wang — APPROVED** [review]
/lgtm
/approve

**Comment by k82cn** [comment]
can we add the steps in makefile?

**Comment by Thor-wl** [comment]
> where does this file come from?

Execute golang UT coverage test for pkg/*

**Comment by Thor-wl** [comment]
> can we add the steps in makefile?

Yes, let me add it.

**Pull request merged**
