### PR TITLE
fix: update job phase when scale up from jobReplicas==0

### PR DESCRIPTION
**Pull request by merryzhou**
Signed-off-by: merryzhou <merryzhou0882@gmail.com>

https://github.com/volcano-sh/volcano/issues/1169

### CODE REVIEW

**Review by hzxuzhonghu — COMMENTED** [review]
https://github.com/volcano-sh/volcano/blob/42b2cf48a9f686d935a55a34d4135cf04ab8bfc2/pkg/controllers/job/job_controller_actions.go#L207-L216

Take care of this logic to prevent initializing twice

**Comment by merryzhou** [comment]
> https://github.com/volcano-sh/volcano/blob/42b2cf48a9f686d935a55a34d4135cf04ab8bfc2/pkg/controllers/job/job_controller_actions.go#L207-L216
> 
> Take care of this logic to prevent initializing twice

It seems impossible to distinguish the reason for update here...

Could you give me some points?

**Comment by wpeng102** [comment]
just use `job.Status.State.Phase` to check job if initiated maybe not accuracy any more. In preemption case also may lead job status change from running to pending.
```
func isInitiated(job *batch.Job) bool {
	if job.Status.State.Phase == "" || job.Status.State.Phase == batch.Pending {
		return false
	}

	return true
}
```

**Comment by wpeng102** [comment]
Maybe we need introduce other job level flag to mark if job has initiated

**Comment by k82cn** [comment]
> Maybe we need introduce other job level flag to mark if job has initiated

A new phase/state maybe better :)

**Comment by merryzhou** [comment]
> > Maybe we need introduce other job level flag to mark if job has initiated
> 
> A new phase/state maybe better :)

how about restarting?

**Pull request closed without merging**
