### PR TITLE
feat:add printing of MemStats in dumpall

### PR DESCRIPTION
**Pull request by xiao-jay**
Add SchedulerMemStats in dumpall.Having schedule MemStats info makes it easier to locate problems.

### CODE REVIEW

**Comment by lowang-bh** [comment]
what does the print result look like?

**Comment by neujie** [comment]
LGTM

**Review by william-wang — APPROVED** [review]
/lgtm

**Comment by lowang-bh** [comment]
It seems not human readable.

**Comment by xiao-jay** [comment]
@neujie Thank you for your help

**Pull request merged**
