### PR TITLE
docs: fix README broken URL

### PR DESCRIPTION
**Pull request by jasondrogba**
the url on README can not access, replace it with correct one

### CODE REVIEW

**Comment by jasondrogba** [comment]
hi, can you review this PR ~ @k82cn 
/assign @k82cn

**Review by hwdef — COMMENTED** [review]
/lgtm
/ok-to-test

**Comment by jasondrogba** [comment]
@hwdef @k82cn hi~ why the workflow is still pending😂

**Comment by Monokaix** [comment]
Please rebase master: )

**Comment by jasondrogba** [comment]
> Please rebase master: )

Thanks, already rebased : )

**Pull request merged**
