### PR TITLE
Lint Fixes

### PR DESCRIPTION
**Pull request by SrinivasChilveri**
some more lint fixes

### CODE REVIEW

**Comment by k82cn** [comment]
@SrinivasChilveri , that'll be better if we can not give enough information by comments.

/cc @asifdxtreme

**Comment by SrinivasChilveri** [comment]
@k82cn , I do agree some comments were not proper. updated withe same with the new commit. if you still feel some more things need update pls do let me know.

**Comment by asifdxtreme** [comment]
lgtm overall

**Pull request merged**
