### PR TITLE
Design doc for VerticalQueueAutoscaler

### PR DESCRIPTION
**Pull request by zbbkeepgoing**
Like hpa in kubernetes, vqa is a custom resource that control resources capacity of queue automatically

Signed-off-by: Binbin Zou <binbin.zou@kyligence.io>

### CODE REVIEW

**Comment by william-wang** [comment]
@zbbkeepgoing Thanks for your PR.  Would you share your use case and design on the weekly meeting?

**Comment by zbbkeepgoing** [comment]
> @zbbkeepgoing Thanks for your PR. Would you share your use case and design on the weekly meeting?

sure, no problem.

**Comment by hwdef** [comment]
please change the signoff, your email is wrong.

**Comment by zbbkeepgoing** [comment]
@william-wang Any suggestions for this design?

**Pull request closed without merging**
