### PR TITLE
upgrade api version of volcano

### PR DESCRIPTION
**Pull request by lucming**
this pr is used to upgrade api version of volcano crds to v1, and ralated issue is:https://github.com/volcano-sh/volcano/issues/2201

### CODE REVIEW

**Comment by lucming** [comment]
CI did not pass because vendor directory and go mod do not match, what shuould i do ?

**Comment by hwdef** [comment]
> CI did not pass because vendor directory and go mod do not match, what shuould i do ?

```shell
go mod tidy && go mod vendor
```

**Comment by lucming** [comment]
> ```shell
> go mod tidy && go mod vendor
> ```

i can't do this,because https://github.com/volcano-sh/apis this project has not been released yet,it lacks something I rely on, and I've mentioned pr ( https://github.com/volcano-sh/apis/pull/81 )

**Comment by hwdef** [comment]
> > ```shell
> > go mod tidy && go mod vendor
> > ```
> 
> i can't do this,because https://github.com/volcano-sh/apis this project has not been released yet,it lacks something I rely on, and I've mentioned pr ( [volcano-sh/apis#81](https://github.com/volcano-sh/apis/pull/81) )

so https://github.com/volcano-sh/apis/pull/81 should be merged first, then this pr will be mergable

**Comment by lucming** [comment]
> so [volcano-sh/apis#81](https://github.com/volcano-sh/apis/pull/81) should be merged first, then this pr will be mergable

Yes, it is.

**Pull request closed without merging**
