### PR TITLE
[cherry-pick] optimize resource comparision functions for performance

### PR DESCRIPTION
**Pull request by hwdef**
Signed-off-by: huone1 <huwanxing@huawei.com>

fix: #2014

### CODE REVIEW

**Comment by k82cn** [comment]
That'll be great to have this feature in mainline firstly :)

**Comment by hwdef** [comment]
> 

Yes, the master branch already had this commit #1769

**Comment by hwdef** [comment]
> That'll be great to have this feature in mainline firstly :)

Yes, the master branch already had this commit https://github.com/volcano-sh/volcano/pull/1769

**Comment by k82cn** [comment]
bwt, you can try this script: https://github.com/volcano-sh/volcano/blob/master/hack/cherry_pick_pull.sh .

**Comment by hwdef** [comment]
> bwt, you can try this script: https://github.com/volcano-sh/volcano/blob/master/hack/cherry_pick_pull.sh .

Thanks!
I need this!

**Pull request merged**
