### PR TITLE
fix job enqueue issue

### PR DESCRIPTION
**Pull request by merryzhou**
Signed-off-by: merryzhou <merryzhou0882@gmail.com>

https://github.com/volcano-sh/volcano/issues/1416

### CODE REVIEW

**Review by zen-xu — APPROVED** [review]

**Comment by Thor-wl** [comment]
It may introduce some unexpected errors. I've rerun the CI for some times but it still fails. Please take a check.

**Comment by merryzhou** [comment]
> It may introduce some unexpected errors. I've rerun the CI for some times but it still fails. Please take a check.

fixed

**Review by jasonliu747 — APPROVED** [review]
/lgtm

**Pull request merged**
