### PR TITLE
api(volcano): add task status to pod

### PR DESCRIPTION
**Pull request by CharlesQQ**
resolve: https://github.com/volcano-sh/volcano/issues/3029

### CODE REVIEW

**Comment by lowang-bh** [comment]
/hold

It's too complex

**Comment by CharlesQQ** [comment]
> It's too complex

can you describe  it more clearly?

**Comment by lowang-bh** [comment]
There are three points:
1. change `NewJobInfo` function is a bad case, you'd better keep it as origin, and put the pod status updating where job is comitted or discard.
2. apiserver calling frequency will cause cluster presure. You'd better to keep this feature close as default.
3. patch oparation can used to do pod updating.

**Comment by Thor-wl** [comment]
> I am recommending event recording and end user can consume those events and do what they want.

+1

**Pull request closed without merging**
