### PR TITLE
update issue template

### PR DESCRIPTION
**Pull request by hwdef**
Use yaml replace markdown, it can provide more styles.
Delete some useless and duplicate questions, such as 
`What would you like to be added`
`Why is this needed:`
replaced by 
`What is the problem you're trying to solve`
`Describe the solution you'd like`
`Additional context`

The modification plan refers to [containerd](https://github.com/containerd/containerd/issues/new/choose).

### CODE REVIEW

**Comment by googs1025** [comment]
can we so add a `Support Request` kind template?

**Comment by googs1025** [comment]
> can we so add a `Support Request` kind template?

I'm not sure if question is of type support

**Comment by hwdef** [comment]
> can we so add a `Support Request` kind template?

I think this duplicates the functionality of enhancement and question

**Comment by Monokaix** [comment]
A little doubt thst is yaml format more user friendly than markdown?

**Comment by hwdef** [comment]
> A little doubt thst is yaml format more user friendly than markdown?

I think so. 

The following is a comparison between yaml and markdown. 

Users can also enter markdown in the input box

image

image

**Comment by Monokaix** [comment]
That's great!

**Comment by Monokaix** [comment]
cc @lowang-bh

**Pull request merged**
