### PR TITLE
update golang version to 1.19.5

### PR DESCRIPTION
**Pull request by yanggangtony**
Signed-off-by: yanggang <gang.yang@daocloud.io>

go1.19.5 have releaed for a time. Update to follow it..
Also go1.20 is released. maybe we should wait for a several versions after ,and follow it.

[go release](https://github.com/golang/go/tags)

### CODE REVIEW

**Review by Thor-wl — COMMENTED** [review]
@yanggangtony Hey, kindly to ask if there is something making sense for Volcano in go v1.19.5?

**Comment by yanggangtony** [comment]
> kindly to ask if there is something making sense for Volcano in go v1.19.5?

no , just upgrade the go version to match the latest go1.19.
but now 1.20 have released. 
may be update to it in a near feature?

Is there a good solve to make go: latest? for no need to update go version again?

@Thor-wl 
thansk for review.

**Comment by wangyang0616** [comment]
It is recommended to postpone the upgrade of the golang version. 

At present, the latest version of k8s supported by Volcano is v1.25, and k8s v1.25 also uses go 1.19. If there is no special requirement, we can adapt k8s v1.27 version, Corresponding to upgrade the major version of golang.

**Comment by Thor-wl** [comment]
> t is recommended to postpone the upgrade of the golang version.
> 
> At present, the latest version of k8s supported by Volcano is v1.25, and k8s v1.25 also uses go 1.19. If there is no special requirement, we can adapt k8s v1.27 version, Corresponding to upgrade the major version of golang.

Acctually, I'm on @wangyang0616 's side.

**Comment by yanggangtony** [comment]
@Thor-wl @wangyang0616 
The intents  `postpone the upgrade of the golang version` i have known ,  version 1.20 will not going to current schedule..

So this pr is keep stale? or wait a 1.19 new version have come then to follow it ? for example 1.19.6 is released ,then follow 1.19.5?  like these way?

thanks yours suggestion.

**Pull request closed without merging**
