### PR TITLE
Fix queue cannot use idle resource issue

### PR DESCRIPTION
**Pull request by wpeng102**
Fix issue https://github.com/volcano-sh/volcano/issues/1168

Root cause refer https://github.com/volcano-sh/volcano/issues/1168#issuecomment-736275104

### CODE REVIEW

**Comment by wpeng102** [comment]
Cluster has 4 cpu and 8G memory.
Queue1 weight is 1, Queue2 weight is 1.

Submit joba to queue1, request 500m cpu, replica=1 min=1
Submit jobb1 ~ jobb5 to queue2, each job request 500m cpu, replica=1, min=1

Queue2 can use 2500m CPU. 

```
[root@wangpeng yaml]# kubectl get po
NAME         READY   STATUS    RESTARTS   AGE
joba-t1-0    1/1     Running   0          27s
jobb1-t1-0   1/1     Running   0          15s
jobb2-t1-0   1/1     Running   0          11s
jobb3-t1-0   1/1     Running   0          8s
jobb4-t1-0   1/1     Running   0          6s
jobb5-t1-0   1/1     Running   0          4s
```

```
[root@wangpeng yaml]# vcctl queue list
Name                     Weight  State   Inqueue Pending Running Unknown 
default                  1       Open    0       0       0       0       
queue1                   1       Open    0       0       1       0       
queue2                   1       Open    0       0       5       0 
```

Node almost allocate all the CPU resources.
```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests     Limits
  --------           --------     ------
  cpu                3850m (96%)  100m (2%)
  memory             190Mi (2%)   390Mi (5%)
  ephemeral-storage  0 (0%)       0 (0%)
  hugepages-1Gi      0 (0%)       0 (0%)
  hugepages-2Mi      0 (0%)       0 (0%)
Events:              <none>

```

**Comment by wpeng102** [comment]
More test cases refer https://github.com/volcano-sh/volcano/issues/1168#issuecomment-736528738

**Comment by hudson741** [comment]
thanks All,it is OK now

**Pull request merged**
