### PR TITLE
feat(core): upgrade controller tools to v0.6.0

### PR DESCRIPTION
**Pull request by shinytang6**
resolves https://github.com/volcano-sh/volcano/issues/1567

### CODE REVIEW

**Comment by william-wang** [comment]
> resolves #1567
@shinytang6 
Thank you for the PR.  
Do you have a verification with the PR to make sure the annotation and label lost issue in #1567 have been fixed?

**Comment by shinytang6** [comment]
> > resolves #1567
> > @shinytang6
> > Thank you for the PR.
> > Do you have a verification with the PR to make sure the annotation and label lost issue in #1567 have been fixed?

l tested it with k8s v1.20 and it worked great, not tried other versions.

**Comment by huone1** [comment]
> > > resolves #1567
> > > @shinytang6
> > > Thank you for the PR.
> > > Do you have a verification with the PR to make sure the annotation and label lost issue in #1567 have been fixed?
> 
> l tested it with k8s v1.20.5 and it worked great, not tried other versions.

**Comment by william-wang** [comment]
@shinytang6  Please make the CI happy.

**Review by william-wang — APPROVED** [review]
/lgtm
/approve

**Comment by Thor-wl** [comment]
> @shinytang6 Please make the CI happy.

It causes by the update of tools in github action machines. I'm trying to fix it.

**Comment by Thor-wl** [comment]
CI has been fixed and please pull and rebase from master branch to make CI happy.
You can execute `git pull --rebase origin/master` to do that. @shinytang6

**Comment by shinytang6** [comment]
> CI has been fixed and please pull and rebase from master branch to make CI happy.
> You can execute `git pull --rebase origin/master` to do that. @shinytang6

done.

**Review by jasonliu747 — APPROVED** [review]
/lgtm
Nice work!

**Pull request merged**
