### PR TITLE
Improve job controller 

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
This is the first step for job controller performance optimization

### CODE REVIEW

**Comment by k82cn** [comment]
please share the test result; we should improve the hot point firstly.

**Comment by hzxuzhonghu** [comment]
please review commit by commit, it is clear what this pr does

**Comment by hzxuzhonghu** [comment]
@k82cn Please let me know if this make sense to you, so i can decide if i should work on fixing ci. Otherwise, i can close it.

**Comment by hzxuzhonghu** [comment]
close, will do it in a separate pr

**Pull request closed without merging**
