### PR TITLE
fix: fix admission not support ip address which will cause ssl error.…

### PR DESCRIPTION
**Pull request by berlinsaint**
Fix [issue](https://github.com/volcano-sh/volcano/issues/2088)

Signed-off-by: maybaby <berlinsaint@126.com>

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
IP is not a good practice as the pod can be down/up dynamically. Do you want to generate certificates dynamically?

**Comment by berlinsaint** [comment]
> IP is not a good practice as the pod can be down/up dynamically. Do you want to generate certificates dynamically?
yes but our ip is vip , there are some cases that we we can't use svc as i point at the issue.  our kube master is on another main kube cluster, so they can't callback the sub kubecluster's svc

**Comment by berlinsaint** [comment]
> IP is not a good practice as the pod can be down/up dynamically. Do you want to generate certificates dynamically?

And i think  this pr is just a small support for the ips, you see that choices is optional, not required

**Comment by hzxuzhonghu** [comment]
Kind of understanding your k8s cluster, that means in your scene, native webhook can not be used.  Looks it make sense.

**Pull request merged**
