### PR TITLE
fix make update-development-yaml will remove other webhooks than disa…

### PR DESCRIPTION
**Pull request by tanberBro**
fix：https://github.com/volcano-sh/volcano/issues/3129

### CODE REVIEW

**Comment by tanberBro** [comment]
@lowang-bh

**Comment by lowang-bh** [comment]
duplicated with PR #3109

**Comment by lowang-bh** [comment]
Hi @tanberBro Thanks for your contributions very much! There is already an PR for that issue.

**Comment by tanberBro** [comment]
sry, I will close.

**Pull request closed without merging**
