### PR TITLE
try get get old pg when new pg not exist

### PR DESCRIPTION
**Pull request by Akiqqqqqqq**
Signed-off-by: Qiuyu Wu <qiuyu.wu@shopee.com>

fix：https://github.com/volcano-sh/volcano/issues/2389

what happen:
after this feature https://github.com/volcano-sh/volcano/pull/2140 applied, error comes when upgrading volcano from 1.4 to 1.6, details showed in https://github.com/volcano-sh/volcano/issues/2389.

this is because volcano-job-controller creates extra pgs with job uid suffix for existing jobs, which are already running, and thus two pgs exist in cluster for one vj. when existing jobs are using over half of the cluster resource already, the new pgs with uid will cause inqueue get larger in proportion AddJobEnqueueableFn (line 334 in pkg/scheduler/plugins/proportion/proportion.go). after inqueue gets larger than realCapability, the new coming jobs will pend forever

### CODE REVIEW

**Comment by Thor-wl** [comment]
Thanks for your contribution. I think it is important for users who upgrades volcano versions from below v1.6.0 to v1.6.0.

**Review by hzxuzhonghu — COMMENTED** [review]
Overall lgtm, just one comment i think the PG construction code can be resued, maybe abstract a `buildPodGroup` function

**Review by william-wang — APPROVED** [review]
/approve

**Pull request merged**
