### PR TITLE
Realias scheduling api version name in package imports

### PR DESCRIPTION
**Pull request by kerthcet**
Signed-off-by: kerthcet <kerthcet@gmail.com>

/kind cleanup

### CODE REVIEW

**Review by hzxuzhonghu — APPROVED** [review]
/lgtm

**Review by hwdef — COMMENTED** [review]
/lgtm

The CI seems to have a problem and needs to be fixed.

**Comment by kerthcet** [comment]
> /lgtm
> 
> 
> 
> The CI seems to have a problem and needs to be fixed.

@hwdef Would you mind to add a ok-to-test, I'll try to dig the root cause.

**Comment by kerthcet** [comment]
It's just for testing, I raised another PR to fix this CI error here https://github.com/volcano-sh/volcano/pull/2532. PTAL, thanks a lot.

**Comment by kerthcet** [comment]
@hwdef would you mind to add LGTM again. it's ready to merge now since the CI is fixed. But I have no idea how to trigger the CI test again. 🙃

**Comment by kerthcet** [comment]
Repushed to trigger the CI.

**Review by hwdef — COMMENTED** [review]
/hold cancel
/lgtm

**Comment by hwdef** [comment]
> @hwdef would you mind to add LGTM again. it's ready to merge now since the CI is fixed. But I have no idea how to trigger the CI test again. 🙃

The volcano's robot does not have a reset command, you can re-trigger CI by submitting it again (the same as you did), or by closing and reopening PR

**Pull request merged**
