### PR TITLE
Release 1.5 vgpu support

### PR DESCRIPTION
**Pull request by archlitchi**
add 4pd vgpu support for volcano. For now, this is only the design doc to be discussed.

### CODE REVIEW

**Comment by Thor-wl** [comment]
Hey, thanks for the contribution. Since v1.5 will be released recently, suggest to add this feature to v1.6 and give a feature review in the weekly meeting if it is convient for you.

**Comment by hwdef** [comment]
Why the emphasis on `4pd`? This is not a universal gpu solution?

**Comment by archlitchi** [comment]
> Hey, thanks for the contribution. Since v1.5 will be released recently, suggest to add this feature to v1.6 and give a feature review in the weekly meeting if it is convient for you.

Thanks, 

> Why the emphasis on `4pd`? This is not a universal gpu solution?

It is universal, emphasis on 4pd because I'm trying to merge the ability of 4pd-vgpu-scheduler(https://github.com/4paradigm/k8s-vgpu-scheduler) into volcano. There are other vgpu plans like Tencent vcuda, aliyun gpu-share,etc.

**Comment by hwdef** [comment]
@archlitchi 
I see, thanks! Looking forward to this feature.

**Comment by Thor-wl** [comment]
> > Hey, thanks for the contribution. Since v1.5 will be released recently, suggest to add this feature to v1.6 and give a feature review in the weekly meeting if it is convient for you.
> 
> Thanks, Next weekly meeting will be held in Feb.18, 15:00-16:00 right? I'll make sure to attend.
> 
> > Why the emphasis on `4pd`? This is not a universal gpu solution?
> 
> It is universal, emphasis on 4pd because I'm trying to merge the ability of 4pd-vgpu-scheduler(https://github.com/4paradigm/k8s-vgpu-scheduler) into volcano. There are other vgpu plans like Tencent vcuda, aliyun gpu-share,etc.

Yeap, welcome to attend next weekly meeting!

**Comment by william-wang** [comment]
@archlitchi , Thank you for your pr. We will review it as soon as possible:)

**Comment by k82cn** [comment]
/approve

LGTM overall :)

**Comment by hwdef** [comment]
Please rebase the latest code to fix CI.

**Comment by william-wang** [comment]
@archlitchi Thanks for your design and implemeation. It's wonderful. 
Would you submit design doc and implemetation in seperated pr to `master` branch? The Volcano 1.6 version will be released from master. Besides, the project will be tracked in issue #2111

**Comment by k82cn** [comment]
let's have a design doc firstly :)

**Pull request closed without merging**
