### PR TITLE
Fix reclaim ut

### PR DESCRIPTION
**Pull request by googs1025**
#### What type of PR is this?
/kind bug

#### What this PR does / why we need it:
- Fix reclaim ut
- print typo fix
#### Which issue(s) this PR fixes:

Fix https://github.com/volcano-sh/volcano/issues/3414#event-12470117977

#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Comment by lowang-bh** [comment]
#3408 has fixed that.

**Comment by googs1025** [comment]
oh! I didn't notice, I will close this PR @lowang-bh

**Pull request closed without merging**
