### PR TITLE
add design doc for usage based scheduling

### PR DESCRIPTION
**Pull request by william-wang**
resolve the issue #1777 
Signed-off-by: william-wang <wang.platform@gmail.com>

### CODE REVIEW

**Comment by Jason-Liu-Dream** [comment]
Is this design like Trimaran(https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/kep/61-Trimaran-real-load-aware-scheduling/README.md) in kubernetes plugins?

**Comment by Thor-wl** [comment]
> Is this design like Trimaran(https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/kep/61-Trimaran-real-load-aware-scheduling/README.md) in kubernetes plugins?

AFAIK, they have the similar decision making process. But this design will conside more factors accroding to the Volcano configurations. Namely, it will foucs on batch scheduling more.

**Review by wpeng102 — APPROVED** [review]
/lgtm

**Pull request merged**
