### PR TITLE
fix queue allocated exceeds capability

### PR DESCRIPTION
**Pull request by aidaizyy**
backgroup: https://github.com/volcano-sh/volcano/issues/1860

### CODE REVIEW

**Comment by aidaizyy** [comment]
In fact, I think it can replace UnderusedResourcesFns. But I did not act in this PR.

**Review by jasonliu747 — CHANGES_REQUESTED** [review]
Hi @aidaizyy thanks for your contribution. Please check CI errors and try to fix it.

**Comment by aidaizyy** [comment]
@jasonliu747 The CI error here is about vcjob controller, but my change is scheduler, it shouldn't matter. I reproduce it locally, sometimes it passes and sometimes it fails. I think this is a CI problem. 
Can you teach me how to re-trigger CI.

**Comment by huone1** [comment]
> @jasonliu747 The CI error here is about vcjob controller, but my change is scheduler, it shouldn't matter. I reproduce it locally without/with this PR many times, sometimes it passes and sometimes it fails. I think this is a CI problem. Can you teach me how to re-trigger CI.
you can delete the state ·vcbatch.Running·， sometimes， CI didn't watch the vcbatch.Running and skip it for the poor performance
https://github.com/volcano-sh/volcano/blob/c2383539e714576c330cafc6dd9031007b611b6d/test/e2e/jobp/job_lifecycle.go#L116

**Comment by Thor-wl** [comment]
> @jasonliu747 The CI error here is about vcjob controller, but my change is scheduler, it shouldn't matter. I reproduce it locally without/with this PR many times, sometimes it passes and sometimes it fails. I think this is a CI problem. Can you teach me how to re-trigger CI.

I'll triger the CI restart once I see the fails.

**Comment by aidaizyy** [comment]
> > @jasonliu747 The CI error here is about vcjob controller, but my change is scheduler, it shouldn't matter. I reproduce it locally without/with this PR many times, sometimes it passes and sometimes it fails. I think this is a CI problem. Can you teach me how to re-trigger CI.
> 
> I'll triger the CI restart once I see the fails.

Now i see success

**Comment by Thor-wl** [comment]
> In fact, I think it can replace UnderusedResourcesFns. But I did not act in this PR.

Yes, I'm ok about that.
/lgtm

**Comment by k82cn** [comment]
> In fact, I think it can replace UnderusedResourcesFns. But I did not act in this PR.

If so, let's replace `UnderusedResourcesFns`. The more callback fns, the more complex :)

**Comment by aidaizyy** [comment]
@k82cn As you said, I removed `UnderusedResourcesFns`. 
cc @Thor-wl

**Comment by Thor-wl** [comment]
If there are modifications later, please update the doc: https://github.com/volcano-sh/volcano/blob/master/docs/design/resource-comparison.md

**Comment by william-wang** [comment]
@aidaizyy The bugfix for below important issue is changed in current pr. Please have a test and make sure the existing fix for following issue works as expected. Thanks.
https://github.com/volcano-sh/volcano/issues/1425

**Comment by aidaizyy** [comment]
@william-wang no problem
This pr can work well to deal with the above issue.

old code: `overused := !attr.allocated.LessEqual(attr.deserved, api.Zero)`
Once a resource is overused, the above result must be true.

new code after issue 1425: `overused := attr.deserved.LessEqual(attr.allocated, api.Zero)`
All resources are overused, the above result is true. I kept this logic.

**Comment by aidaizyy** [comment]
> If there are modifications later, please update the doc: https://github.com/volcano-sh/volcano/blob/master/docs/design/resource-comparison.md

@Thor-wl  I did not change the resource comparison func. Do i need to change this file?

**Comment by Thor-wl** [comment]
> > If there are modifications later, please update the doc: https://github.com/volcano-sh/volcano/blob/master/docs/design/resource-comparison.md
> 
> @Thor-wl I did not change the resource comparison func. Do i need to change this file?

It's OK to me. But I agree with the suggestion @william-wang gave.

**Comment by aidaizyy** [comment]
@william-wang thanks for your suggestion.
There is indeed a problem here.
My previous code:
```go
ssn.AddAllocatableFn(pp.Name(), func(queue *api.QueueInfo, candidate *api.TaskInfo) bool {
		attr := pp.queueOpts[queue.UID]

		toAllocated := attr.allocated.Clone()
		toAllocated.Add(candidate.Resreq)
		allocatable := toAllocated.LessEqual(attr.deserved, api.Zero)
		if !allocatable {
			klog.V(3).Infof("Queue <%v>: deserved <%v>, allocated <%v>; Candidate <%v>: resource request <%v>",
				queue.Name, attr.deserved, attr.allocated, candidate.Name, candidate.Resreq)
		}

		return allocatable
	})
```
If the deserved does not change, there will be no problem. but if the deserved is reduced to less than allocated, then even if there are enough other resources, it cannot continue to be scheduled.

My latest code:
```go
ssn.AddAllocatableFn(pp.Name(), func(queue *api.QueueInfo, candidate *api.TaskInfo) bool {
		attr := pp.queueOpts[queue.UID]

		free, _ := attr.deserved.Diff(attr.allocated, api.Zero)
		allocatable := candidate.Resreq.LessEqual(free, api.Zero)
		if !allocatable {
			klog.V(3).Infof("Queue <%v>: deserved <%v>, allocated <%v>; Candidate <%v>: resource request <%v>",
				queue.Name, attr.deserved, attr.allocated, candidate.Name, candidate.Resreq)
		}

		return allocatable
	})
```
I think this problem has been solved.

@william-wang @Thor-wl 
Please review this PR again, thank you.

**Comment by aidaizyy** [comment]
@Thor-wl @k82cn @william-wang 
If you have time, please review this PR. I think this bug is more important because it breaks the semantics of `capability`

**Comment by william-wang** [comment]
@aidaizyy I will take a look as soon as possible :)

**Review by william-wang — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
