### PR TITLE
Added ttl validation in admission controller

### PR DESCRIPTION
**Pull request by SrinivasChilveri**
ttl validation in admission controller.

travis result

VolcanoTravis_ 2019-05-15 11-45-14

### CODE REVIEW

**Comment by SrinivasChilveri** [comment]
@hzxuzhonghu ,added validation in admission controller. pls do have a look.

**Comment by hzxuzhonghu** [comment]
/lgtm

@SrinivasChilveri Could you add a default value for it when it is nil?

**Comment by TommyLike** [comment]
> /lgtm
> 
> @SrinivasChilveri Could you add a default value for it when it is nil?

Would be conflicted to your design:
```
	// ttlSecondsAfterFinished limits the lifetime of a Job that has finished
	// execution (either Completed or Failed). If this field is set,
	// ttlSecondsAfterFinished after the Job finishes, it is eligible to be
	// automatically deleted. If this field is unset,
	// the Job won't be automatically deleted. If this field is set to zero,
	// the Job becomes eligible to be deleted immediately after it finishes.
	// +optional
```

/lgtm

**Comment by SrinivasChilveri** [comment]
> /lgtm
> 
> @SrinivasChilveri Could you add a default value for it when it is nil?

can i add default value as 10 ?

**Comment by hzxuzhonghu** [comment]
@TommyLike  Yeah， should update the desc.

>can i add default value as 10 ?

I think this should be large enough to allow users to check logs / results. I prefer 1 day,  @k82cn @TommyLike WDYT

**Pull request merged**
