### PR TITLE
[squash]Automatically generate the appropriate CRD

### PR DESCRIPTION
**Pull request by wanshicheng**
Details refer to: [#1921](https://github.com/volcano-sh/volcano/pull/1921)
Signed-off-by: wanshicheng <wanshicheng@qq.com>

### CODE REVIEW

**Comment by wanshicheng** [comment]
I believe I'm right this time ^_^

**Review by shinytang6 — COMMENTED** [review]
Thx, lgtm overall )

**Comment by jasonliu747** [comment]
> I believe I'm right this time ^_^

Indeed you were right.
/lgtm

**Review by hwdef — COMMENTED** [review]
Next time you encounter this situation, you can directly use the git rebase command to compress, Instead of reopening a pr. 😊

https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec

**Comment by wanshicheng** [comment]
> Next time you encounter this situation, you can directly use the git rebase command to compress, Instead of reopening a pr. 😊
> 
> https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec

Thx, got new skills.

**Pull request merged**
