### PR TITLE
delete redundant import alias

### PR DESCRIPTION
**Pull request by Shoothzj**

### CODE REVIEW

**Review by hwdef — COMMENTED** [review]
It is not recommended to delete v1alpha1, which should be added automatically by IDE, such as vscode, if deleted, it will be added again,

**Comment by Shoothzj** [comment]
@hwdef Thanks for your review. Let me check if later

**Comment by Shoothzj** [comment]
From I tested in vscode. It doesn't auto add v1alpha by vscode. Did I missing something?
image

**Comment by hwdef** [comment]
> From I tested in vscode. It doesn't auto add v1alpha by vscode. Did I missing something? image

I tested and it looks like this autofill will only fill 'v1'

```
v1 "k8s.io/api/core/v1"
```

so, this PR is great. Thank you!

/lgtm

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by wangyang0616** [comment]
cc @william-wang 
Please help to review it, and if possible, help to trigger CICD manually. 
Thanks!

**Pull request merged**
