### PR TITLE
feat: support min available at task level

### PR DESCRIPTION
**Pull request by shinytang6**

### CODE REVIEW

**Comment by Thor-wl** [comment]
@shinytang6 Please close and reopen this PR

**Comment by shinytang6** [comment]
> @shinytang6 Please close and reopen this PR

l am still improving and testing this pr, l will update it whenever it is ready for review :)

**Comment by k82cn** [comment]
maybe we can separate this PR into several smaller ones.

**Comment by Thor-wl** [comment]
Please resolve the conflicts

**Comment by Thor-wl** [comment]
Is there any process about this feature？ @shinytang6

**Pull request closed without merging**
