### PR TITLE
Introducing Volcano Guru on Gurubase.io

### PR DESCRIPTION
**Pull request by kursataktas**
Hello team,

I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.

I wanted to update you that I've manually added the [Volcano Guru](https://gurubase.io/g/volcano) to Gurubase. Volcano Guru uses the data from this repo and data from the [docs](https://volcano.sh/en/docs/) to answer questions by leveraging the LLM.

In this PR, I showcased the "Volcano Guru", which highlights that Volcano now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.

Additionally, if you want me to disable Volcano Guru in Gurubase, just let me know that's totally fine.

### CODE REVIEW

**Comment by JesseStutler** [comment]
I'm totally fine with it, seems that it can help volcano promote. /cc @hwdef @Monokaix

**Comment by kursataktas** [comment]
Hey @JesseStutler thanks for the review.

Gurubase is currently neither an open-source nor a commercial product. Initially, we created 'Anteon Guru' for our users, and after seeing how happy they were with it, we thought, 'Why not create a Guru for all possible OSS tools out there?' So, there’s no direct business relationship between Anteon and Gurubase. It’s simply how it came to be.

**Comment by JesseStutler** [comment]
If you are only using it internally, why do you need to modify volcano’s README.md to add guru URL?

**Comment by william-wang** [comment]
@kursataktas I had a look at the Volcano Guru. It's cool and great to have it :)

**Comment by kursataktas** [comment]
> If you are only using it internally, why do you need to modify volcano’s README.md to add guru URL?

We didn't use it internally. We originally created Anteon Guru specifically for Anteon users, and later decided to create additional gurus for users of other tools. If you think this addition adds value to Volcano users, I'd be happy to see my contribution in Volcano's README. If not, I'd be glad to receive feedback to improve it.

**Comment by kursataktas** [comment]
Hi everyone,

I’d like to update you on the release of the Maintainer Panel feature on Gurubase. With this panel, you can add, remove, or update data sources, as well as change the logo and more. You can find the details [here](https://github.com/getanteon/gurubase?tab=readme-ov-file#how-to-claim-a-guru). 

In the near future, I’m planning to include analytics insights in this panel, such as the number of questions asked, the most frequently asked ones, and more. I’ll be sure to update this thread once it’s available. However, in case I miss it, I highly recommend joining our [Discord channel](https://discord.gg/9CMRSQPqx6) to stay updated.

If you’d prefer that I don’t update this thread anymore, please let me know.

**Comment by kursataktas** [comment]
Hello Everyone,

We recently released the embeddable "Ask AI" widget, which allows you to integrate your Guru’s Q&A capability into websites, documentation, and more.

The installation process is straightforward, as explained in [this GitHub repository](https://github.com/getanteon/gurubase-widget).

You can see it in action on the [Anteon](https://getanteon.com/) and [NetAlertX](https://netalertx.com/) websites.

**Comment by hwdef** [comment]
Does ray use Gura?
image

**Comment by kursataktas** [comment]
> Does ray use Gura? image

I didn’t understand what you meant.

**Comment by hwdef** [comment]
There is an `ask AI` button in the lower right corner of the official website of the  [ray](https://docs.ray.io/en/master/index.html) project. Looks similar to Gura's functionality?

**Comment by kursataktas** [comment]
> There is an `ask AI` button in the lower right corner of the official website of the [ray](https://docs.ray.io/en/master/index.html) project. Looks similar to Gura's functionality?

No, they don't use Gurubase. I hope they will use it someday. :)

**Comment by kursataktas** [comment]
Hello Everyone,

I want to share an exciting update about Gurubase. We've recently released several great features that I think you'll find interesting.

### 1. Slack & Discord Integration
You can now add your Guru as a bot to Slack and Discord, allowing you to ask questions instantly. More details here: [Discord Bot Integration](https://docs.gurubase.ai/integrations/discord-bot).

### 2. Analytics Dashboard
Track what your users ask your Guru and gain valuable insights. This feature is available on the "My Gurus" page. If you haven’t maintained your Guru yet, I highly recommend doing so to access your analytics. More information about claiming your Guru can be found [here](https://github.com/Gurubase/gurubase?tab=readme-ov-file#how-to-claim-a-guru).
image

### 3. API Support
All Guru functionalities are now accessible via API. You can ask questions, edit data sources, and more using our API endpoints. Here is the [API Doc](https://docs.gurubase.ai/api-reference/introduction).

### 4. Codebase Indexing
We now support indexing codebases from GitHub repositories to generate answers for related queries. This feature is available for select Gurus. If you don’t see the "Codebase Indexed" label on your Guru edit page and would like access, please let me know, I’d be happy to enable it for you!
image

Let me know if you have any questions or feedback!

**Comment by kursataktas** [comment]
Hey @volcano-sh-bot,

I wanted to update you that we’ve released the Gurubase GitHub bot!
This means you can now integrate your Guru into your repository,  so users can ask it questions directly through GitHub issues. By default, the Gurubase bot automatically responds to newly opened issues, but you can customize its behavior if needed.

You can see it in action in [this demo issue](https://github.com/Gurubase/gurubase/issues/248).
More information about the bot can be found [here](https://docs.gurubase.ai/integrations/github-bot).

gurubase-github-bot-demo

-----

_Note: As I mentioned in my first update on this thread, please let me know if you’d prefer not to receive updates here._

**Pull request merged**
