### PR TITLE
feat: add shinytang6 as reviewer

### PR DESCRIPTION
**Pull request by shinytang6**
My contribution as follows:

### module contribution include:
* scheduler
* controller manager

### main feature contribution
* [Add MaxRequeueNum as a controller-manager param](https://github.com/volcano-sh/volcano/pull/1087)
* [Support min available in task level(In Progress)](https://github.com/volcano-sh/volcano/pull/1193)
* [Mutate default of job spec](https://github.com/volcano-sh/volcano/pull/1170)

### bug fix
job controller bug:
* https://github.com/volcano-sh/volcano/pull/1084

### scheduler bug:
* https://github.com/volcano-sh/volcano/pull/1110
* https://github.com/volcano-sh/volcano/pull/1111

### other bugs(script/doc):
* https://github.com/volcano-sh/volcano/pull/1077
* https://github.com/volcano-sh/volcano/pull/1201
* https://github.com/volcano-sh/volcano/pull/1208

Take part in weekly community meeting, feature design and some PR reviews.

Totally, i've contributed 8 merged PRs and 3 is on the way, hope to contribute more to the community.

### CODE REVIEW

**Comment by Thor-wl** [comment]
Hey! Please list your contributions. Another tip: please add yourself to the `reviewer` list in the OWNERs file of the module you are familar with such as `scheduler`

**Comment by shinytang6** [comment]
> Hey! Please list your contributions. Another tip: please add yourself to the `reviewer` list in the OWNERs file of the module you are familar with such as `scheduler`

ok, done

**Comment by k82cn** [comment]
/lgtm
/approve

Thanks very much for your contribution!

**Pull request merged**
