### PR TITLE
Support reclaim/preempt gang job which allocated resources equal or lesser than MinAvailable

### PR DESCRIPTION
**Pull request by nkflash**
@Thor-wl please check this design and implementation

### CODE REVIEW

**Comment by nkflash** [comment]
fix https://github.com/volcano-sh/volcano/issues/2321

**Review by Thor-wl — COMMENTED** [review]
Thanks for your optimiztion! Here are some suggestions as follows.
* Please separate the design doc from the implementation in 2 PRs. As the classical process of contribution, the community will review the desgin first. Once it is settled, the implementation follows.
* Perhaps we can add these design as part of `preemption` and `reclaim` desgin doc instead of an individual doc. In general, a new feature comes with a new desgin doc.
* It seems a little rough to just enable preemption and reclaim to evict pods from other jobs. A vicitim job with incomplete roles may not work well. For example, a victim spark job with only part of `executor` left. I think we should give more details about the evict strategy. For example, once a job is selected as victim, all of the pods or elastic pods **must** be evicted.
* Perhaps we can refer to the [elastic scheduler](https://github.com/volcano-sh/volcano/blob/master/docs/design/elastic-scheduler.md) and [TDM plugin](https://github.com/volcano-sh/volcano/blob/master/docs/design/tdm-plugin.md) as reference. This optimization can be implemented within the consideration with the 2 features mentioned above.
* Please execute `git commit --signoff xxx` to add personal signature. It is required by CI.
* Please execute `go fmt xxx` to make code verification happy.

**Comment by Thor-wl** [comment]
> Thanks for your optimiztion! Here are some suggestions as follows.
> 
> * Please separate the design doc from the implementation in **2** PRs. As the classical process of contribution, the community will review the desgin first. Once it is settled, the implementation follows.
> * Perhaps we can add these design as part of `preemption` and `reclaim` desgin doc instead of an individual doc. In general, a new feature comes with a new desgin doc.
> * It seems a little rough to just enbale preemption and reclaim to evict pods from other jobs. A vicitim job with incomplete roles may not work well. For example, a victim spark job with only part of `executor` left. I think we should give more details about the evict strategy. For example, once a job is selected as victim, all of the pods or elastic pods **must** be evicted.
> * Perhaps we can refer to the [elastic scheduler](https://github.com/volcano-sh/volcano/blob/master/docs/design/elastic-scheduler.md) and [TDM plugin](https://github.com/volcano-sh/volcano/blob/master/docs/design/tdm-plugin.md) as reference. This optimization can be implemented in the consideration with the 2 features mentioned above.

**Comment by Thor-wl** [comment]
@nkflash Please follow the code of conduct and format the code to pass the CI. Thanks.

**Comment by nkflash** [comment]
> @nkflash Please follow the code of conduct and format the code to pass the CI. Thanks.

Sorry, I am busy with some other workload. I will finish this later.

**Pull request closed without merging**
