### PR TITLE
Add default trueValue for plugin config: EnabledBestNode for all plugins

### PR DESCRIPTION
**Pull request by jiangkaihua**
Signed-off-by: jiangkaihua <jiangkaihua1@huawei.com>

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
@jiangkaihua Would you please first open a pr on master branch and then backport it?

**Comment by jiangkaihua** [comment]
> @jiangkaihua Would you please first open a pr on master branch and then backport it?

https://github.com/volcano-sh/volcano/pull/935

**Comment by hzxuzhonghu** [comment]
IC, thanks. we need the link

**Pull request merged**
