### PR TITLE
 TDM plugins add timezone suppose

### PR DESCRIPTION
**Pull request by Jason-Liu-Dream**
1. some times we didn't know timezone of default date, especially when running in a container.
2. timezone like UTC is not very readable in our region，so we need to translate time，that not friendly，so let‘s make some things.

### CODE REVIEW

**Comment by hwdef** [comment]
Why not change the timezone by mounting the file?

**Comment by william-wang** [comment]
@Jason-Liu-Dream thanks for the PR. Please follow the guideline, open a issue firstly and more contributors can fully discuss there.  Thanks:)

**Comment by Jason-Liu-Dream** [comment]
> @Jason-Liu-Dream thanks for the PR. Please follow the guideline, open a issue firstly and more contributors can fully discuss there. Thanks:)
ok，i create a issue，#2277，let‘s discuss at here

**Comment by Jason-Liu-Dream** [comment]
> Why not change the timezone by mounting the file?



> Why not change the timezone by mounting the file?

did you mean to say this way to change：mount /etc/localtime to container？I think we need keep use utc to system，because it's a convention and other this may use it. but in this plugins，we can use this label to help us more intuitive.

**Comment by Jason-Liu-Dream** [comment]
> Why not change the timezone by mounting the file?


did you mean to say this way to change：mount /etc/localtime to container？I think we need keep use utc to system，because it's a convention and other this may use it. but in this plugins，we can use this label to help us more intuitive.

**Pull request closed without merging**
