### PR TITLE
refactor session part and statement part to improve code readability

### PR DESCRIPTION
**Pull request by googs1025**
#### What type of PR is this?
/kind cleanup

#### What this PR does / why we need it:
- refactor session part to improve readability. We can reduce if-else branches and reduce code complexity
- refactor statement part
#### Does this PR introduce a user-facing change?

```release-note
None
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs
None
```

### CODE REVIEW

**Review by lowang-bh — COMMENTED** [review]
/lgtm

**Comment by Monokaix** [comment]
> /hold
Any consideration here?

**Comment by lowang-bh** [comment]
Session refact is ok. The statement refact has some information lose. The log is important and should be easy to debug issue in production env.

**Comment by googs1025** [comment]
> Session refact is ok. The statement refact has some information lose. The log is important and should be easy to debug issue in production env.

I have kept most of the logs.
can you help me to review it, and point it out to me if I missed anything and I will modify it immediately.

**Comment by googs1025** [comment]
/close
No longer active , so I close this

**Pull request closed without merging**
