### PR TITLE
Bump Kube-Batch version to latest

### PR DESCRIPTION
**Pull request by asifdxtreme**
Fixes: #159

### CODE REVIEW

**Comment by asifdxtreme** [comment]
Because of this commit the build is failing https://github.com/volcano-sh/kube-batch/commit/3b939e20582ee88c04d5f9415666d8db3159a504  
Should we add the code back?
@k82cn @TommyLike

**Comment by k82cn** [comment]
we have to get https://github.com/volcano-sh/volcano/pull/162 merged to fix that.

**Comment by k82cn** [comment]
please help to fix the CI

**Comment by k82cn** [comment]
any process?

**Pull request closed without merging**
