### PR TITLE
update arm's yaml, and upgrade makefile to automatically generate arm's yaml

### PR DESCRIPTION
**Pull request by hwdef**

### CODE REVIEW

**Comment by Yikun** [comment]
@hwdef I guess this might no needed after https://github.com/volcano-sh/volcano/pull/1571 merged, could you help to review on it? Thanks!

**Comment by hwdef** [comment]
> @hwdef I guess this might no needed after #1571 merged, could you help to review on it? Thanks!

ok, I think we should fix CI first.

**Pull request merged**
