### PR TITLE
fix misuse object name issue

### PR DESCRIPTION
**Pull request by elinx**
#1980

### CODE REVIEW

**Comment by justadogistaken** [comment]
I guess the original naming is fine.

**Comment by elinx** [comment]
> I guess the original naming is fine.

I would say yes if you mean the functionality, it works fine and they are all even not used in their methods. But one could reasonably assume that they were all copied and pasted from the `Allocate` action which I would like to change to their real name for readability and scalability(may be used in the future).

**Review by shinytang6 — COMMENTED** [review]
pls fix the DCO

/lgtm

**Comment by justadogistaken** [comment]
> > I guess the original naming is fine.
> 
> I would say yes if you mean the functionality, it works fine and they are all even not used in their methods. But one could reasonably assume that they were all copied and pasted from the `Allocate` action which I would like to change to their real name for readability and scalability(may be used in the future).

Got it

**Comment by elinx** [comment]
> pls fix the DCO /lgtm

fixed, thanks

**Review by shinytang6 — APPROVED** [review]
/approve

**Pull request merged**
