### PR TITLE
bugfix(installer): fix grafana template fromat error in volcano-monitoring-latest.yaml

### PR DESCRIPTION
**Pull request by Xu-Wentao**
Some values like `\{\{` can't be recognized by grafana, we need to change them to `\\{\\{`.

### CODE REVIEW

**Comment by william-wang** [comment]
Triger the ci.

**Comment by Xu-Wentao** [comment]
> Triger the ci.

I'm new here, can you tell me how to triger the ci, :)

**Comment by Monokaix** [comment]
Fixed by https://github.com/volcano-sh/volcano/pull/3262

**Pull request closed without merging**
