### PR TITLE
Revert "fix(scheduler): use nodeMap to fix anti-affinity problem"

### PR DESCRIPTION
**Pull request by Thor-wl**
Reverts volcano-sh/volcano#1430

### CODE REVIEW

**Review by shinytang6 — COMMENTED** [review]
Is there any bad effect this pr may cause?

**Comment by Thor-wl** [comment]
> Is there any bad effect this pr may cause?

I'll merge this PR after the upgrade of k8s version for there is some conflicts.

**Comment by shinytang6** [comment]
This should also be merged into the new version.
/cc @Thor-wl

**Comment by Thor-wl** [comment]
> This should also be merged into the new version.
> /cc @Thor-wl

/asign @Thor-wl

**Pull request merged**
