### PR TITLE
add resource comparison doc

### PR DESCRIPTION
**Pull request by Thor-wl**
ref: https://github.com/volcano-sh/volcano/issues/1525
Signed-off-by: Thor-wl <13164644535@163.com>

### CODE REVIEW

**Review by Tammy-kunyu — COMMENTED** [review]
I have a think about that.And here comes the situation:if  A(i,1)>=B(j,2) is true, do something.is A(i,1)>=B(j,2) can be reasonable？

**Review by william-wang — APPROVED** [review]
/lgtm
/approve

**Review by jasonliu747 — COMMENTED** [review]
/lgtm
Nice work!

**Comment by Thor-wl** [comment]
> I have an idea about that.And here comes the situation:if A(i,1)>=B(j,2) is true, do something. A(i,1)>=B(j,2) can be reasonable？

Yes. Sometimes we just need there exists one dimension satisfing certain condition and ignore others' dimensions.

**Review by shinytang6 — APPROVED** [review]
/lgtm
/approve

**Comment by Thor-wl** [comment]
I'll merge this commit without considering the CI for it is only a doc and there are more than two approves.

**Review by jasonliu747 — APPROVED** [review]

**Review by wpeng102 — APPROVED** [review]

**Review by wpeng102 — APPROVED** [review]
/lgtm

**Pull request merged**
