### PR TITLE
Update owners: add archlitchi to approver in scheduler plugins

### PR DESCRIPTION
**Pull request by archlitchi**
i'm responsible for deviceshare plugin for volcano. it provides the volcano-vgpu feature, i'll continue to provide more device-sharing features for more manufactures, and integrate MIG and MPS for NVIDIA

### CODE REVIEW

**Comment by Monokaix** [comment]
xref: https://github.com/volcano-sh/community/issues/64

**Comment by Monokaix** [comment]
Please sign off your commit.

**Review by william-wang — APPROVED** [review]
/approve

**Pull request merged**
