### PR TITLE
remove repeated code.

### PR DESCRIPTION
**Pull request by YesterdayxD**
Line 56-58 has same effect.

### CODE REVIEW

**Comment by YesterdayxD** [comment]
or 
```
if pod.Spec.SchedulerName != job.Spec.SchedulerName {
		pod.Spec.SchedulerName = job.Spec.SchedulerName
	}
```
aim to make the name
@hzxuzhonghu

**Comment by hzxuzhonghu** [comment]
@YesterdayxD Good catch， i prefer https://github.com/volcano-sh/volcano/pull/627#issuecomment-567386295

**Comment by hzxuzhonghu** [comment]
And  one step further, i would like to deprecate the `JobSpec.SchedulerName`, because for volcano, it is meaningless to allow specifying a different scheduler name.

**Comment by k82cn** [comment]
> i would like to deprecate the `JobSpec.SchedulerName`

Please do not do that, that'll make user set schedulerName for each pod-template. We can validate it by admission controller.

**Comment by YesterdayxD** [comment]
Please add lgtm label.

**Comment by k82cn** [comment]
@hzxuzhonghu , is that ok for you?

**Comment by hzxuzhonghu** [comment]
yeah 
/lgtm

**Pull request merged**
