### PR TITLE
Add a new `volcano-latest.yaml` with `Always` imagePullPolicy

### PR DESCRIPTION
**Pull request by Yikun**
#### What would you like to be added:
Add a new `volcano-latest.yaml` for users want to always use remote new latest image.

#### Why is this needed:
some users want to always use remote new latest image.

Signed-off-by: Yikun Jiang <yikunkero@gmail.com>

#### How to test?
```
make update-development-yaml
# To make sure only policy replaced by Always
diff installer/volcano-latest-arm64.yaml installer/volcano-development-arm64.yaml
diff installer/volcano-latest.yaml installer/volcano-development.yaml
```
Closes: https://github.com/volcano-sh/volcano/issues/2072

### CODE REVIEW

**Comment by Yikun** [comment]
This change is not enough, because CI are using `IfNotPresent` image policy to make sure latest are using latest PR to test.

**Comment by Yikun** [comment]
We'd better add a `volcano-latest.yaml` with `Always` to make sure users download latest images.

And keep the `volcano-developer.yaml` as current behavior to keep same UX for developer.

**Comment by Yikun** [comment]
cc @hwdef could you take a look I think you are very familar with this.

Also cc @Thor-wl @william-wang How about this? Add a new yaml, and still keep origin one for developers and CI.

**Comment by hwdef** [comment]
I think it is also good to keep only one file. Because the tag is `latest`, user want to use latest images. And because image is layered, very little traffic is generated if the mirror has not changed.

It would also work if you want to save two files, but I recommend adding documentation explaining how the two files are different

**Comment by Yikun** [comment]
@hwdef 
- dev suffix yaml is for developers and CI, dev can use

```
TAG: latest make images
k apply dev.yml
```

to validate dev work.

- latest suffix yaml is for users, they always want to download latest published images.

Yep, we need doc, latest.yml will be shown in website, dev.yml will be shown in developer doc.

**Pull request closed without merging**
