### PR TITLE
registe nodegroup plugin to factory

### PR DESCRIPTION
**Pull request by wuyueandrew**
#3367 fixed and tested on my laptop

### CODE REVIEW

**Review by hwdef — COMMENTED** [review]
/lgtm

**Comment by lowang-bh** [comment]
@wuyueandrew please make the CI happy! You can close and reopen it to trigger the ci.

**Comment by Monokaix** [comment]
Hi，please also cherry-pick it to release 1.9.

**Review by william-wang — APPROVED** [review]
/approve

**Pull request merged**
