### PR TITLE
Retain job's resources after job finished successfully or failed

### PR DESCRIPTION
**Pull request by hzxuzhonghu**

### CODE REVIEW

**Comment by k82cn** [comment]
any backgroup of this PR?

**Comment by hzxuzhonghu** [comment]
Users are unable to see the output, as the pods removed.

**Comment by k82cn** [comment]
> Users are unable to see the output, as the pods removed.

so what's your solution? any pros/cons? It's really a hard work to review code directly.

**Comment by hzxuzhonghu** [comment]
The most urgent requirement is : 1. retain the workload log, we have no way except keeping the pod after job finished(no matter successfully or failed). 2. retain the pvc,  for this we need to add an option in API, which should be a separate pr.

**Pull request closed without merging**
