### PR TITLE
Scheduler in tree

### PR DESCRIPTION
**Pull request by kevin-wangzefeng**
generated with script in https://github.com/volcano-sh/volcano/pull/287

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
The retest does not take effect on travis ci

**Comment by kevin-wangzefeng** [comment]
/hold
Wait for final conclusion of https://github.com/volcano-sh/volcano/issues/241.

**Comment by TommyLike** [comment]
coverage can be fixed in the following patches

**Pull request merged**
