### PR TITLE
fix the security alert from Kubernetes

### PR DESCRIPTION
**Pull request by Thor-wl**
fix: https://github.com/volcano-sh/volcano/security/dependabot/example/custom-plugin/go.sum/k8s.io%2Fkubernetes/open
Signed-off-by: Thor-wl <13164644535@163.com>

### CODE REVIEW

**Comment by hwdef** [comment]
> fix: https://github.com/volcano-sh/volcano/security/dependabot/example/custom-plugin/go.sum/k8s.io%2Fkubernetes/open Signed-off-by: Thor-wl [13164644535@163.com](mailto:13164644535@163.com)

404 not found.

**Comment by Thor-wl** [comment]
> 

Oh, sorry, It may be only open for project admins. The alert suggests to upgrade K8s to at least v1.19.15

**Review by shinytang6 — APPROVED** [review]
/lgtm

**Pull request merged**
