### PR TITLE
Remove escape character to fix broken grafana dashboard configuration

### PR DESCRIPTION
**Pull request by shaobo76**
This PR tries to fix the error in #2717. Verified in my local environment.

### CODE REVIEW

**Comment by wangyang0616** [comment]
Please make ci happy.

**Comment by shaobo76** [comment]
> Please make ci happy. You can view the details failure reasons and repair methods through the detail of the failed ci

Done. Thanks for pointing that out.

**Comment by wangyang0616** [comment]
Can you help to trigger the running of ci test cases, thanks! @william-wang @Thor-wl

**Comment by Thor-wl** [comment]
> Can you help to trigger the running of ci test cases, thanks! @william-wang @Thor-wl

OK, triggered

**Review by hwdef — COMMENTED** [review]
I think this file in generate by `./hack/generate-yaml.sh`, you should modify it.

**Comment by shaobo76** [comment]
> I think this file in generate by `./hack/generate-yaml.sh`, you should modify it.

Finished. And it seems that remove the escape character is the right way.

**Review by Thor-wl — APPROVED** [review]

**Review by Thor-wl — APPROVED** [review]

**Comment by shaobo76** [comment]
Thank you for the approval. What can i do to pass those tests? @Thor-wl

**Review by hwdef — COMMENTED** [review]
please squash your commit to one

**Review by hwdef — COMMENTED** [review]
/ok-to-test
/lgtm

**Comment by wangyang0616** [comment]
After the current PR is merged, there is an error in the CI operation. 

May I ask what content we have manually modified about grafana.yaml, can you describe it in detail? It is not easy for diffwenjian to see.

The CI error message is as follows:
image

**Pull request merged**
