### PR TITLE
fix: Fix the wrong comments in the example

### PR DESCRIPTION
**Pull request by gaocegege**
PTAL

Signed-off-by: cegao <cegao@tencent.com>

### CODE REVIEW

**Comment by k82cn** [comment]
@Thor-wl can we enable /retest action, close/reopen may make others confused :)

**Comment by gaocegege** [comment]
> @Thor-wl can we enable /retest action, close/reopen may make others confused :)

+1. It's confusing.

**Comment by Thor-wl** [comment]
> @Thor-wl can we enable /retest action, close/reopen may make others confused :)
Click CI “detail” and jump to the action page. There is a "Re-run jobs" button

**Pull request merged**
