### PR TITLE
bump volcano api definition to v1.6.0 in dependencies

### PR DESCRIPTION
**Pull request by Thor-wl**
update the dependencies apis to date.
Signed-off-by: Thor-wl <13164644535@163.com>

### CODE REVIEW

**Comment by kevin-wangzefeng** [comment]
Would suggest to update PR title and commit message to "bump volcano api definition to v1.6.0 in dependencies"

**Comment by Thor-wl** [comment]
> Would suggest to update PR title and commit message to "bump volcano api definition to v1.6.0 in dependencies"

OK. Done.

**Pull request merged**
