### PR TITLE
🦄 refactor: simplify code by define DimensionDefaultValue as float64

### PR DESCRIPTION
**Pull request by kingeasternsun**
Signed-off-by: kingeasternsun <kingeasternsun@gmail.com>
By define DimensionDefaultValue as float64, we can simplify the function of Diff and setDefaultValue

### CODE REVIEW

**Comment by kingeasternsun** [comment]
> hwdef

I think redundancy is the enemy of code quality.

**Comment by hwdef** [comment]
I maintain a neutral opinion on this PR, waiting for other reviewers' opinions

**Pull request closed without merging**
