### PR TITLE
Delete current incorrect benchmark testing results

### PR DESCRIPTION
**Pull request by JesseStutler**
related with #3856

### CODE REVIEW

**Review by hwdef — COMMENTED** [review]
Delete it directly? No modifications?

**Comment by lowang-bh** [comment]
It is just added in https://github.com/volcano-sh/volcano/pull/3730, so why remove it?

**Comment by JesseStutler** [comment]
> Delete it directly? No modifications?



> It is just added in #3730, so why remove it?

These results and testing methods are quite incorrect. The reason why it's incorrect is explained in this issue: https://github.com/volcano-sh/volcano/issues/3856. Currently we don't have much time to fix it, but we will arrange to re-test next year.

**Comment by lowang-bh** [comment]
> > Delete it directly? No modifications?
> 
> > It is just added in #3730, so why remove it?
> 
> These results and testing methods are quite incorrect. The reason why it's incorrect is explained in this issue: #3856. Currently we don't have much time to fix it, but we will arrange to re-test next year.

/lgtm

**Pull request merged**
