### PR TITLE
Bump Scheduler

### PR DESCRIPTION
**Pull request by asifdxtreme**
https://github.com/volcano-sh/volcano/issues/219

### CODE REVIEW

**Comment by k82cn** [comment]
please help to include this one: https://github.com/volcano-sh/scheduler/pull/26

**Comment by k82cn** [comment]
BTW, can we let volcano-sh-bot to do this regularly, e.g. every night?

**Comment by asifdxtreme** [comment]
> please help to include this one: [volcano-sh/scheduler#26](https://github.com/volcano-sh/scheduler/pull/26)

I have added these changes but 1 gang scheduling test case is failing https://travis-ci.com/volcano-sh/volcano/jobs/207010805#L555

**Pull request merged**
