### PR TITLE
Add initContainer GPU number when calculating GPUs

### PR DESCRIPTION
**Pull request by kerthcet**
/kind feature

1. Add GPU in initContainer into consideration when calculating GPU requests, also inspired by https://github.com/volcano-sh/volcano/pull/1692/files#r918632925
2. code cleanup

### CODE REVIEW

**Comment by Thor-wl** [comment]
@kerthcet Please update the vendor. Generally LGTM for me.
/lgtm

**Comment by kerthcet** [comment]
> @kerthcet Please update the vendor. Generally LGTM for me. /lgtm

I ran with `make verify`, it passed, but the test still failed, can you provide more details.

**Comment by Thor-wl** [comment]
> I ran with `make verify`, it passed, but the test still failed, can you provide more details.

No worries. It' OK now.

**Review by Thor-wl — APPROVED** [review]

**Pull request merged**
