### PR TITLE
Inherit kube-batch owners

### PR DESCRIPTION
**Pull request by k82cn**
Scheduler is an import part of Volcano, so inherit kube-batch owners. If any comments/suggestions, please let me know :)

### CODE REVIEW

**Comment by k82cn** [comment]
@animeshsingh , @hex108 , @hzxuzhonghu , add you into OWNER as you're already approver of kube-batch. Please let me know whether that's ok to you :)

**Comment by hex108** [comment]
LGTM. Thanks!

**Comment by hzxuzhonghu** [comment]
LGTM. thanks

**Comment by k82cn** [comment]
Thanks all, I'd like to get this one merged firstly :)

**Comment by kevin-wangzefeng** [comment]
/approve
发件人：Klaus Ma <notifications@github.com>
收件人：volcano-sh/volcano <volcano@noreply.github.com>
抄 送：Kevin Wang <kevinwzf0126@gmail.com>;Review requested <review_requested@noreply.github.com>
时间：2019-07-04 08:41:45
主 题：Re: [volcano-sh/volcano] Inherit kube-batch owners (#281)


Thanks all, I'd like to get this one merged firstly :)

**Pull request merged**
