### PR TITLE
Remove duplicate import in session.go

### PR DESCRIPTION
**Pull request by zbbkeepgoing**

### CODE REVIEW

**Review by hwdef — COMMENTED** [review]
/lgtm

**Review by Thor-wl — APPROVED** [review]

**Review by william-wang — APPROVED** [review]
/lgtm

**Comment by zbbkeepgoing** [comment]
@hwdef @Thor-wl  Lgtm label removed due to rerunning CI, please help to relabel.

**Review by hwdef — COMMENTED** [review]
/lgtm

**Pull request merged**
