### PR TITLE
Skipped task if no candidate nodes.

### LINKED ISSUE #838: Observed a panic: invalid argument to Intn（when batchNodeOrder function return err)
> /kind bug
**What happened**:
I added a schedule plugin ，and used a function named batchNodeOrder. This funciton return a error when nodes unmeet required. But, the volcano-schedule crash.

**What you expected to happen**:
Add the job backup to queue, and run ok

**How to reproduce it (as minimally and precisely as possible)**:
```
			node := ssn.BestNodeFn(task, nodeScores)
			if node == nil {
				node = util.SelectBestNode(nodeScores)
			}
```
After these, add the node judge.  

**Anything else we need to know?**:

**Environment**:
- Volcano Version:  0.4
- Kubernetes version (use `kubectl version`): 1.17.3
- Cloud provider or hardware configuration: arm64
- OS (e.g. from /etc/os-release): unbuntu 13.2
- Kernel (e.g. `uname -a`):
- Install tools:
volcano-shedule-crash

### PR DESCRIPTION
**Pull request by k82cn**
fix #838 

Signed-off-by: Klaus Ma <klaus1982.cn@gmail.com>

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
The real cause is from `node = util.SelectBestNode(nodeScores)`, where nodeScores is empty.

**Comment by k82cn** [comment]
> The real cause is from `node = util.SelectBestNode(nodeScores)`, where nodeScores is empty.

The nodeScores is built from candidateNodes.

**Comment by hzxuzhonghu** [comment]
@zishen added a customized plugin, which functions on `PrioritizeNodes`

**Comment by k82cn** [comment]
> @zishen added a customized plugin, which functions on `PrioritizeNodes`

xref https://github.com/volcano-sh/volcano/issues/838#issuecomment-636323529

**Comment by hzxuzhonghu** [comment]
Please note:  It is possible when `candidateNodes` is not empty but `nodeScores` is.

**Comment by k82cn** [comment]
> Please note: It is possible when `candidateNodes` is not empty but `nodeScores` is.

when? `PrioritizeNodes` should only sort `candidateNodes`.

**Comment by hzxuzhonghu** [comment]
@zishen Please help explain your use case. I remember that batchFn fails, and returns

```
	batchNodeScore, err := batchFn(task, nodes)
	if err != nil {
		klog.Errorf("Error in Calculating batch Priority for the node, err %v", err)
		return nodeScores
	}

```

**Pull request merged**
