### PR TITLE
Optimization register controller log

### PR DESCRIPTION
**Pull request by hwdef**
fix: #1620

### CODE REVIEW

**Review by shinytang6 — CHANGES_REQUESTED** [review]
Could you also help enhance the version, git SHA, built time? They are `Not provided` now.

**Comment by hwdef** [comment]
@shinytang6 

I used `make vc-controller-manager` to build bin, and I get the following results

image


So, I think the code about show git SHA and build time is correct.

**Review by jasonliu747 — APPROVED** [review]
/lgtm

**Review by shinytang6 — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
