### PR TITLE
Remove vendor

### LINKED ISSUE #2858: Remove vendor
**What happened**:

**What you expected to happen**:

Down vendor by `go mod` instead of including it in source code.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Volcano Version:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by xiao-jay**
fix #2858 #2841 
After Go 1.12,Go default use go modules,because Go modules have truly achieved reproducible builds，vender may will use offline build,but this requirement is likely the choice of a minority in volcano,So decide to delete the vendor in volcano.

### PR Describe：
1、delete vendor
2、[modify hack/verify-vendor.sh to hack/verify-gomod.sh ](https://github.com/volcano-sh/volcano/pull/2863/commits/aa28ac9b4dab8aa0cf790a4c645d09af36b61937)
```
➜  hack git:(remove-vendor) ✗ ./verify-gomod.sh
running 'go mod tidy' for repo root
SUCCESS: go.mod Verified.
```

### CODE REVIEW

**Comment by lowang-bh** [comment]
LGTM

**Comment by xiao-jay** [comment]
@william-wang @k82cn @wangyang0616 Could you please review this pr?

**Review by hwdef — COMMENTED** [review]
/lgtm

**Review by hwdef — COMMENTED** [review]
/lgtm

**Comment by lowang-bh** [comment]
Forget to comment 1 issue:  `make manifests` depend on the vendors.

**Comment by xiao-jay** [comment]
> 

ok，so now need to change `make manifests` from depend on the vendors to depend on the gomod?
@lowang-bh

**Comment by lowang-bh** [comment]
> 
> ok，so now need to change `make manifests` from depend on the vendors to depend on the gomod? @lowang-bh

I have no idea. how about @hwdef @wangyang0616 @william-wang

**Comment by william-wang** [comment]
@xiao-jay need to fix it as soon as possible. Let's generate the vendor by `gomod vendor` prior to `make manifests`

**Pull request merged**
