### PR TITLE
update image version from latest to v1.6.0

### PR DESCRIPTION
**Pull request by hwdef**
The images version in the branch of each version should be consistent with the branch version

### CODE REVIEW

**Review by Thor-wl — APPROVED** [review]

**Comment by william-wang** [comment]
@hwdef It was a miss for the 1.6 release. Thanks so much for the bugfix.  Please make the ci work well.

**Comment by hwdef** [comment]
@Thor-wl @william-wang 
The CI of this PR has passed, please review again.

**Pull request merged**
