### PR TITLE
controllers.yaml clusterRole add  flow.volcano.sh

### PR DESCRIPTION
**Pull request by wangzhipeng**
增加flow.volcano.sh权限

### CODE REVIEW

**Comment by lowang-bh** [comment]
It is ok to me.

**Comment by wangzhipeng** [comment]
@william-wang

**Comment by lowang-bh** [comment]
> It is ok to me.

One issue left to be solve: please run make generate-yaml to update deployment yaml

**Review by Thor-wl — APPROVED** [review]

**Comment by lowang-bh** [comment]
There is already a same pr merged.
/close

**Pull request closed without merging**
