### PR TITLE
Allow setting user name in ssh plugin

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
Fixes： #403

To support specifying ssh user when running volcano job.

```
apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: lm-mpi-job
spec:
  minAvailable: 3
  schedulerName: volcano
  plugins:
    ssh: ["--user=volcano"]    # specify volcano username
    svc: []
  tasks:
    ...

```

### CODE REVIEW

**Comment by k82cn** [comment]
@hzxuzhonghu , would you help to print output of `mpirun` under `volcano` user, and show the ownership and permission of `.ssh`?

**Comment by TommyLike** [comment]
@hzxuzhonghu  Does this change mean the user need to start the container via the identical user configured here?

**Comment by hzxuzhonghu** [comment]
>would you help to print output of mpirun under volcano user, and show the ownership and permission of .ssh?

Good point, the ownership of the id_rsa is root, not the user itself. I think this is expected by k8s.

So we canot do this..

**Comment by TommyLike** [comment]
> So we canot do this..

Does this mean we can't print the permission or we can not address feature like this?

**Comment by hzxuzhonghu** [comment]
Yep, i can not think of a perfect solution.

**Comment by TommyLike** [comment]
> Yep, i can not think of a perfect solution.

It should be ok if the `.ssh` folder is created by kubernentes.

**Comment by TommyLike** [comment]
plus, this is what I found in the MPI test:
```
root@mpi-mpimaster-0:~# ls -al
total 20
drwx------ 1 root root 4096 Aug  7 06:25 .
drwxr-xr-x 1 root root 4096 Aug  7 06:25 ..
-rw-r--r-- 1 root root 3106 Oct 22  2015 .bashrc
-rw-r--r-- 1 root root  148 Aug 17  2015 .profile
drwxr-xr-x 2 root root 4096 Aug  7 06:25 .ssh
```

**Comment by hzxuzhonghu** [comment]
Yes, i looked into this and found that the volume mount by kubelet is owned by root. Currently, k8s does not support user setting. So i think it is a blocker for this.

Workaround maybe change the ownership in container. But this requires the image including some tools like sudo, chown.

**Comment by k82cn** [comment]
@hzxuzhonghu , let's move the discussion to issue and close this PR; we can open another PR if necessary.

**Comment by hzxuzhonghu** [comment]
ok

**Pull request closed without merging**
