### PR TITLE
update go to 1.21

### PR DESCRIPTION
**Pull request by hwdef**
Volcano has adapted to k8s1.29 and k8s1.30 will be released soon. We should update the go language version to be consistent with k8s

### CODE REVIEW

**Comment by Monokaix** [comment]
We'd better add some info like volcano has adapted k8s 1.29 and k8s has used go 1.21 and so we should keep consistent it. Also please update docker build base image to 1.21.

**Comment by hwdef** [comment]
> We'd better add some info like volcano has adapted k8s 1.29 and k8s has used go 1.21 and so we should keep consistent it. Also please update docker build base image to 1.21.

Thanks for your suggestions. I fixed this

**Review by william-wang — APPROVED** [review]

**Pull request merged**
