### PR TITLE
Remove case sentitive files to avoid collided paths

### PR DESCRIPTION
**Pull request by shinytang6**
My newly cloned project has collided paths (case-sensitive paths on a case-insensitive filesystem)

### CODE REVIEW

**Comment by Thor-wl** [comment]
Well, it may not influence the project build and running. I don't think removing these three files directly is a good idea for the later newers to review design docs.

**Comment by hzxuzhonghu** [comment]
we should rename them by the naming convention `xxx_yyy`.

**Comment by shinytang6** [comment]
> Well, it may not influence the project build and running. I don't think removing these three files directly is a good idea for the later newers to review design docs.

lt indeed affected my local development to a certain extent. The working space was modified when I cloned the project for the first time.

image

lt was introdueced in commit https://github.com/volcano-sh/volcano/commit/277b0a1dd8c026f4a4d73d52b68c4108f4c91be5. And I did not delete the three files, but updated the latest two files which l think is reservationWorkflow.png & reservationDesign.png to uppercase ReservationWorkflow.png & ReservationDesign.png

**Comment by shinytang6** [comment]
> we should rename them by the naming convention `xxx_yyy`.

I think there are two files (ReservationWorkflow.png & ReservationDesign.png) that are duplicate, is it right? @Thor-wl

**Comment by Thor-wl** [comment]
> > we should rename them by the naming convention `xxx_yyy`.
> 
> I think there are two files (ReservationWorkflow.png & ReservationDesign.png) that are duplicate, is it right? @Thor-wl

No, They are different picture files.

**Comment by Thor-wl** [comment]
> we should rename them by the naming convention `xxx_yyy`.

Perhaps we should make a rule for image files name. There are different name styles in folder volcano.sh/volcano/docs/design/images/

**Comment by Thor-wl** [comment]
relete PR:https://github.com/volcano-sh/volcano/pull/1081

**Comment by shinytang6** [comment]
close due to #1081 was merged.

**Pull request closed without merging**
