### PR TITLE
Fix: All pods is existing when restart count exceed max retry

### PR DESCRIPTION
**Pull request by william-wang**
cherry-pick #1719

Signed-off-by: lubingtan <lubingtan@126.com>

### CODE REVIEW

**Comment by k82cn** [comment]
Why this PR was merged without CI passed?

**Comment by Thor-wl** [comment]
Some pre-installed clients such as ginkgo and golint in Github action CI machines has been update from v1 to v2, which introduces a lot of adoption work. This adoption can been refered to https://github.com/volcano-sh/volcano/pull/1932. This commits has been merged to master branch but not to other branches for it's not a code bug fix.

**Comment by Thor-wl** [comment]
> Why this PR was merged without CI passed?

Some pre-installed clients such as ginkgo and golint in Github action CI machines has been update from v1 to v2, which introduces a lot of adoption work. This adoption can been refered to https://github.com/volcano-sh/volcano/pull/1932. This commits has been merged to master branch but not to other branches for it's not a code bug fix.

**Pull request merged**
