### PR TITLE
chore: Replace deprecation `ioutil` fucntions and add depguard rules in `.golangci.yml`

### PR DESCRIPTION
**Pull request by dongjiang1989**
1. Go 1.16 deprecated several `io/ioutil` functions.

`ioutil.ReadFile` -> `os.ReadFile`

ref: https://pkg.go.dev/io/ioutil

2. Add depguard rules in `.golangci.yml`

3. fix golangci-lint warning
```bash
$ ./hack/verify-golangci-lint.sh
checking whether golangci-lint has been installed
installing golangci-lint .
golangci/golangci-lint info checking GitHub for tag 'v1.54.2'
golangci/golangci-lint info found version: 1.54.2 for v1.54.2/linux/amd64
golangci/golangci-lint info installed /home/runner/work/volcano-sh/volcano/bin/golangci-lint
begin run golangci-lint
level=info msg="[config_reader] Config search paths: [./ /home/runner/work/volcano/volcano/src/github.com/volcano-sh/volcano /home/runner/work/volcano/volcano/src/github.com/volcano-sh /home/runner/work/volcano/volcano/src/github.com /home/runner/work/volcano/volcano/src /home/runner/work/volcano/volcano /home/runner/work/volcano /home/runner/work /home/runner /home /]"
level=info msg="[config_reader] Used config file .golangci.yml"
level=info msg="[lintersdb] Active [11](https://github.com/volcano-sh/volcano/actions/runs/11738190031/job/32700238716#step:5:12) linters: [deadcode depguard gofmt goimports gosimple govet ineffassign staticcheck unused varcheck whitespace]"
level=info msg="[loader] Go packages loading at mode 575 (deps|exports_file|files|imports|name|compiled_files|types_sizes) took 2m[15](https://github.com/volcano-sh/volcano/actions/runs/11738190031/job/32700238716#step:5:16).339428093s"
level=warning msg="[runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused."
level=warning msg="[runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter. Replaced by unused."
....
```

### CODE REVIEW

**Review by hwdef — COMMENTED** [review]
/lgtm

**Comment by dongjiang1989** [comment]
Thanks @hwdef  Please re-check it

**Comment by hwdef** [comment]
Please fix the CI

**Comment by dongjiang1989** [comment]
> Please fix the CI

Hmmm.... Maybe main branch CI pipeline fail ...

**Comment by JesseStutler** [comment]
Please rebase the new master branch because CI has been fixed: https://github.com/volcano-sh/volcano/pull/3817

**Comment by dongjiang1989** [comment]
> Please rebase the new master branch because CI has been fixed: #3817

Great! @JesseStutler . thanks.

**Review by hwdef — COMMENTED** [review]
/ok-to-test
/lgtm

**Comment by hwdef** [comment]
@lowang-bh @Monokaix Please take a look

**Comment by Monokaix** [comment]
Please squash to one commit.

**Comment by dongjiang1989** [comment]
> Please squash to one commit.

Thanks @Monokaix 
Can we use github's `squash and merge` mode?

**Comment by Monokaix** [comment]
> > Please squash to one commit.
> 
> Thanks @Monokaix Can we use github's `squash and merge` mode?

How to config that?

**Comment by Monokaix** [comment]
> > Please squash to one commit.
> 
> Thanks @Monokaix Can we use github's `squash and merge` mode?

It's good habit for developer to keep a clean commit: )

**Comment by dongjiang1989** [comment]
> > > Please squash to one commit.
> > 
> > 
> > Thanks @Monokaix Can we use github's `squash and merge` mode?
> 
> How to config that?

Maybe ref: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests

**Comment by dongjiang1989** [comment]
@hwdef  Please add `/lgtm`, thanks

**Pull request merged**
