### PR TITLE
fix duplicate preemptee in victims

### PR DESCRIPTION
**Pull request by xiaoanyunfei**

### CODE REVIEW

**Review by hzxuzhonghu — APPROVED** [review]

**Comment by k82cn** [comment]
@xiaoanyunfei , can you give more detail about this PR?

**Comment by xiaoanyunfei** [comment]
> @xiaoanyunfei , can you give more detail about this PR?

if namespaceOrderEnabled,
there is chance to call `addVictim(preemptee)` for the same preemptee 

> https://github.com/volcano-sh/volcano/blob/master/pkg/scheduler/plugins/drf/drf.go#L165
>https://github.com/volcano-sh/volcano/blob/master/pkg/scheduler/plugins/drf/drf.go#L193

**Comment by hzxuzhonghu** [comment]
DCO is required

**Pull request merged**
