### PR TITLE
feat(scheduler): add most allocated algo to nodeorder

### PR DESCRIPTION
**Pull request by shinytang6**
As per discussion at one regular meeting, nodeorder should support the `mostallocated` algorithm.
Signed-off-by: shinytang6 <1074461480@qq.com>

### CODE REVIEW

**Comment by k82cn** [comment]
LGTM overall :)

**Comment by Thor-wl** [comment]
@shinytang6 Please resolve the conflictions.

**Comment by shinytang6** [comment]
> @shinytang6 Please resolve the conflictions.

ok, done

**Review by zen-xu — APPROVED** [review]

**Pull request merged**
