### PR TITLE
Support configuring `enqueue` action param

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
This is based on @SrinivasChilveri 's work #389

### CODE REVIEW

**Comment by hzxuzhonghu** [comment]
@k82cn ptal

**Comment by hzxuzhonghu** [comment]
ping @k82cn

**Comment by k82cn** [comment]
Please update to following format:

```
actions: "enqueue, reclaim, allocate, backfill, preempt"
configurations:
- actions:
  - name: enqueue
    arguments:
      overcommit-factor: 1.2
tiers:
- plugins:
  - name: priority
  - name: gang
  - name: conformance
- plugins:
  - name: drf
  - name: predicates
  - name: proportion
  - name: nodeorder
  - name: binpack
```

**Comment by k82cn** [comment]
In the future, we may update plugin to the following format.

```
actions: "enqueue, reclaim, allocate, backfill, preempt"
plugins:
- "priority, gang, conformance"
- "drf, predicates, proportion, nodeorder, binpack"
configurations:
- actions:
  - name: enqueue
    arguments:
      overcommit-factor: 1.2
- plugins:
  - name: drf
    arguments:
      weight: 10
```

**Comment by hzxuzhonghu** [comment]
```
actions: "enqueue, reclaim, allocate, backfill, preempt"
plugins:
- "priority, gang, conformance"
- "drf, predicates, proportion, nodeorder, binpack"
configurations:
- name: enqueue
  arguments:
    overcommit-factor: 1.2
- name: drf
  arguments:
    weight: 10
```

I donot think this is a good api, there is duplicate actions. There is no difference in the compatibility aspect.

**Comment by k82cn** [comment]
> I donot think this is a good api, there is duplicate actions.

Think it again and again :)

**Comment by hzxuzhonghu** [comment]
I am not sure what you mean. SInce i have no bandwidth on this, will close it atm

**Pull request closed without merging**
