### PR TITLE
fix: set leaderelection's ctx that can sense signal in controller

### PR DESCRIPTION
**Pull request by rfyiamcool**
### change

set leaderelection's ctx that can sense signal in controller.

### CODE REVIEW

**Comment by lowang-bh** [comment]
LGTM. Thanks for  your contribution.

**Review by hwdef — COMMENTED** [review]
please rebase your commit, square 2 commits to 1 commit.
And FIX the DCO CI.

**Comment by rfyiamcool** [comment]
> please rebase your commit, square 2 commits to 1 commit. And FIX the DCO CI.

done 😁

**Comment by hwdef** [comment]
@wangyang0616 
Please trigger the CI

**Comment by wangyang0616** [comment]
> @wangyang0616 Please trigger the CI

Please help trigger CI. Thanks! @william-wang

**Comment by william-wang** [comment]
The ci is triggered.

**Review by hwdef — COMMENTED** [review]
/lgtm

**Review by william-wang — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
