### PR TITLE
add UT coverage report for v1.5.0

### PR DESCRIPTION
**Pull request by Thor-wl**
Signed-off-by: Thor-wl <13164644535@163.com>

### CODE REVIEW

**Comment by william-wang** [comment]
We do not have to maintain such a big file in source code. It is about 1M. We could provide a readme to describe how to generate the report if someone care about it.

**Comment by Thor-wl** [comment]
> We do not have to maintain such a big file in source code. It is about 1M. We could provide a readme to describe how to generate the report if someone care about it.

I think it's ok though the file is 1M. It's also regular to provide a UT report when launching a new release.

**Review by shinytang6 — APPROVED** [review]
/lgtm

**Pull request merged**
