### PR TITLE
upgrade kube-state-metrics image versio to v2.0.0-beta from v1.9.7

### PR DESCRIPTION
**Pull request by lengrongfu**
Fixes: https://github.com/volcano-sh/volcano/issues/3564

To avoid too big a version change, only a minor version was upgraded.

`v1.9.8` version having multi arch image. https://explore.ggcr.dev/?image=registry.k8s.io%2Fkube-state-metrics%2Fkube-state-metrics:v1.9.8

### CODE REVIEW

**Comment by Monokaix** [comment]
Welcome and thanks for contribution! And have you tested it with [volcano-monitoring-latest.yaml](https://github.com/volcano-sh/volcano/blob/master/installer/volcano-monitoring-latest.yaml) deployed?

**Comment by william-wang** [comment]
@lengrongfu Thanks for your contrinbution. Have triggered the ci :)

**Comment by lengrongfu** [comment]
> Welcome and thanks for contribution! And have you tested it with [volcano-monitoring-latest.yaml](https://github.com/volcano-sh/volcano/blob/master/installer/volcano-monitoring-latest.yaml) deployed?

pod can success running.

image
image

**Comment by Monokaix** [comment]
Thanks for your contribution! volcano forked `kube-state-metrics` repo and add some custuom metrics, the repo is here: https://github.com/volcano-sh/kube-state-metrics.git, and the image released from this repo has been upload to dockerhub, image name is `volcanosh/kube-state-metrics:v2.0.0-beta`, you can try that and update the image name to it by modifying this pr.

**Comment by lengrongfu** [comment]
> Thanks for your contribution! volcano forked `kube-state-metrics` repo and add some custuom metrics, the repo is here: https://github.com/volcano-sh/kube-state-metrics.git, and the image released from this repo has been upload to dockerhub, image name is `volcanosh/kube-state-metrics:v2.0.0-beta`, you can try that and update the image name to it by modifying this pr.

Thanks, update to `volcanosh/kube-state-metrics:v2.0.0-beta`.

**Comment by Monokaix** [comment]
Hi, you can use `git commit --ame --no-edit -s` and force push again to re-trigger ci.

**Comment by Monokaix** [comment]
/retitle upgrade kube-state-metrics image versio to v2.0.0-beta from v1.9.7

**Comment by Monokaix** [comment]
Hi, please also change the title and description.

**Pull request merged**
