### PR TITLE
queue realcapability change to min dimension of queue capability and cluster realcapability

### PR DESCRIPTION
**Pull request by flyingfang**
issue: #3204

### CODE REVIEW

**Comment by Monokaix** [comment]
Hi, please add ut and use git -s to pass DCO  check.

**Comment by william-wang** [comment]
@flyingfang please fix the ci failure :)

**Comment by lowang-bh** [comment]
Hi, @flyingfang , as #3219 has been merged to fix that issue, you can rebase it and update this pr as its UT.

**Comment by Monokaix** [comment]
/priority/important-soon

**Pull request closed without merging**
