### PR TITLE
add reviewer and approver for alcorj-mizar and Thor-wl

### PR DESCRIPTION
**Pull request by Thor-wl**
1. add approver and reviewer for Thor-wl
2. add approver for alcorj-mizar
Signed-off-by: Thor <1187526662@qq.com>

### CODE REVIEW

**Comment by k82cn** [comment]
please share your contribution :)

**Comment by Thor-wl** [comment]
> please share your contribution :)

@alcorj-mizar has proposed and contriubted to Volcano metrics which is designed as a main feature in v1.1. His work makes the scheduling of Volcano and the current cluster condition visible. In addition, he has taken part in discussion about a lot of main feature design and ouputed some good ideas.

**Comment by k82cn** [comment]
please list your contribution, e.g. merged PR, open issues and so on.

**Comment by Thor-wl** [comment]
> please list your contribution, e.g. merged PR, open issues and so on.

My contribution as follows:
1. module contribution
* scheduler(such as enqueue action, allocate action, etc)
* controllermanager(such job controller)
* e2e 
2. main feature contribution
* [support Arm platform](https://github.com/volcano-sh/volcano/pull/1000)
* [support resource reservation](https://github.com/volcano-sh/volcano/pull/1044)
3. bug fix
* [capability bug](https://github.com/volcano-sh/volcano/pull/995)
* [framework bug](https://github.com/volcano-sh/volcano/pull/923)
* [job controller bug](https://github.com/volcano-sh/volcano/pull/903/files)
4. others
* take part in some design and feature discussion such as metrics
* reconstruct volcano website
* open 14 issues considering some bugs and optimization
* daily issue and PR review
Totally, i've contributed 28 merged PR and 1 is on the way, which rank 5 in the community. The total code contribution is about 5k.

**Comment by k82cn** [comment]
@Thor-wl , thanks for your contribution; that's ok to me 👍 

If no objection, I'm going to merge this PR next monday :)

**Comment by Thor-wl** [comment]
> @Thor-wl , thanks for your contribution; that's ok to me 👍
> 
> If no objection, I'm going to merge this PR next monday :)

Thank you!

**Comment by Thor-wl** [comment]
close this PR for label `do-not-merge/invalid-owners-file`. Reopen the PR:https://github.com/volcano-sh/volcano/pull/1103

**Pull request closed without merging**
