### PR TITLE
[cherry-pick for release-1.9]fix pg controller create redundancy podGroup when schedulerName isn't matched

### PR DESCRIPTION
**Pull request by liuyuanchun11**
fix issue #3671

cherry-pick from #3672

Check whether the value of pod.spec.schedulerName is matched before creating a podGroup.

### CODE REVIEW

**Comment by hwdef** [comment]
I think when cherrypick, the source branch should be master

**Review by hwdef — COMMENTED** [review]
I think when cherrypick, the source branch should be master

**Comment by hwdef** [comment]
cherrypick should operate on only one commitId, not multiple commitIDs

/hold

**Comment by liuyuanchun11** [comment]
> cherrypick should operate on only one commitId, not multiple commitIDs
> 
> /hold

It's cherry-pick from the master branch.

**Comment by hwdef** [comment]
I thnik the commit ID is same with the master

**Pull request merged**
