### PR TITLE
fix calculate inqueue resource bug in opensession

### PR DESCRIPTION
**Pull request by zbbkeepgoing**
Fix Issue: https://github.com/volcano-sh/volcano/issues/2213

Signed-off-by: Binbin Zou <zbbkeepgoing@163.com>

### CODE REVIEW

**Comment by zbbkeepgoing** [comment]
I'm a bit confused about e2e and lint, my code doesn't get these errors and runs fine locally. Is it possible that this error for e2e is because the sleep time of busybox is too short?

- lint error

TEY79Jmg73

e2e error
image

busybox sleep time (e2e error)
image

**Review by Thor-wl — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
