### PR TITLE
Improve performance: remove priorityclass

### PR DESCRIPTION
**Pull request by hzxuzhonghu**
Remove the mutex simultaneously, which is used to protect priorityclass

### CODE REVIEW

**Comment by k82cn** [comment]
Any data about the improvement?

**Comment by hzxuzhonghu** [comment]
I have no test data, but from the mutex race in `calcPGMinResources`, it should have some improvement

**Comment by k82cn** [comment]
> I have no test data, but from the mutex race in `calcPGMinResources`, it should have some improvement

please provide performance benchmark for this pr.

**Comment by hzxuzhonghu** [comment]
This is a minor improve, i do not think it is worth to do benchmark for every improvement. And BTW we do not have any tools and   cluster to do that yet.

**Comment by k82cn** [comment]
that's suprised to me that we got this PR merged without addressing related comments.

>  And BTW we do not have any tools and cluster to do that yet.

Any issue to trace this requirement?

**Pull request merged**
