### PR TITLE
Automatically generate the appropriate CRD

### PR DESCRIPTION
**Pull request by wanshicheng**
I can't  install the chart directly in version v1.21.5 of  k8s. I update some  file so that we can directly install with chart.
Signed-off-by: wanshicheng wanshicheng@qq.com

### CODE REVIEW

**Comment by william-wang** [comment]
@wanshicheng Would you like to provide the install step/command and the error information?

**Comment by wanshicheng** [comment]
> @wanshicheng Would you like to provide the install step/command and the error information?

command:
```
helm install volcano ./volcano -n volcano-system --create-namespace
```

error msg:
```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
```

I can install with follow command:
```
helm install volcano ./volcano -n volcano-system --set basic.crd_version=bases --create-namespace
```

I don't think it's very convenient. Users need to know the version of K8S.

**Comment by Thor-wl** [comment]
Pls fix the DCO @wanshicheng

**Comment by Thor-wl** [comment]
Pls fix the DCO by executing `git commit --signoff  xxx`.

**Comment by wanshicheng** [comment]
> Pls fix the DCO by executing `git commit --signoff xxx`.

Sorry，this is my first pr. I don't know much about the DCO. I think the problem is that the sign off include chinese word?
```
Signed-off-by: 万仕诚 <wanshicheng@qq.com>
```

**Review by hwdef — COMMENTED** [review]
please squash you commits

**Comment by hwdef** [comment]
> > Pls fix the DCO by executing `git commit --signoff xxx`.
> 
> Sorry，this is my first pr. I don't know much about the DCO. I think the problem is that the sign off include chinese word?

Welcome to the volcano community~
DCO now looks correct

**Pull request closed without merging**
